appveyor.yml

The url used to download has been removed and this causes the build to fail.
It is only required to configure it using the new -Version parameter.

fixing maven installation in AppVeyor

---

src/test/groovy/org/asciidoctor/maven/test/AsciidoctorHttpMojoTest.groovy
src/test/groovy/org/asciidoctor/maven/test/AsciidoctorMojoTestHelper.groovy

Instead of using the default mojo port (2000) during http test, find the
first available port on the host an use it during tests.
#171

fix(test): use a random available port on http test

---

.gitignore
appveyor.yml
pom.xml

A part from upgrading the version of the `maven-invoker-plugin` (2.0.0) and maven (3.3.9), I replaced the way Maven is installed.
Now it is download/installed directly without using chocolately. That way we don't need to wait for a package to be published in choco.
Thanks to @yegor256 and this article http://www.yegor256.com/2015/01/10/windows-appveyor-maven.html.

Fixes issue #194

---

src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java

Simplified from previous PR. See #197 for details

Skip processing on not existing source directory

---

README.adoc

A quick way for users to discover the latest deployed artifact version.

Add badge for Maven Central artifact

---

README.adoc

Looks like I butchered the link syntax in the original PR #213 .
Thanks @abelsromero for noticing.

Fix link for Maven Central badge

---

README.adoc
pom.xml
src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java
src/main/java/org/asciidoctor/maven/AsciidoctorZipMojo.java
src/main/java/org/asciidoctor/maven/io/AsciidoctorFileScanner.java
src/test/groovy/org/asciidoctor/maven/test/AsciidoctorHttpMojoTest.groovy
src/test/groovy/org/asciidoctor/maven/test/AsciidoctorMojoExtensionsTest.groovy
src/test/groovy/org/asciidoctor/maven/test/AsciidoctorMojoTest.groovy
src/test/groovy/org/asciidoctor/maven/test/AsciidoctorRefreshMojoTest.groovy
src/test/groovy/org/asciidoctor/maven/test/AsciidoctorZipMojoTest.groovy
src/test/groovy/org/asciidoctor/maven/test/plexus/MockPlexusContainer.groovy
src/test/resources/src/asciidoctor/relative-path-treatment/_this_is_ignored/ignored.adoc
src/test/resources/src/asciidoctor/relative-path-treatment/level-1-1/level-2-2/_this_is_ignored/ignored.adoc

This PR fixes issues:
- #187 and #217: being able to exclude/filter the resources that are copied into the output directory.
- #196: using asciidoctor-diagram with asciidoctor-pdf requires copying the resources before the AsciiDoc documents are rendered. ->_I added this change because it was just moving 2 lines of code_
Following the approach in [PR 192](https://github.com/asciidoctor/asciidoctor-maven-plugin/pull/193) I have added the `maven-filtering` library to allow defining sets of resources like in this example:
````
<resources>
<resource>
<directory>DIRECTORY</directory>
<include>**/*.jpg</include>
<include>**/*.gif</include>
<exclude>**/.svn</exclude>
</resource>
<resource>
<directory>DIRECTORY_2</directory>
<include>**/*.java</include>
<exclude>**/.class</exclude>
</resource> …
```

Adds support to define resources directories with include/exclude filters

---

README.adoc
pom.xml
src/it/article-html-command/pom.xml
src/it/article-html/pom.xml
src/it/book-html/pom.xml
src/it/resource-filtering/invoker.properties
src/it/resource-filtering/pom.xml
src/it/resource-filtering/src/main/doc/sample.asciidoc
src/it/resource-filtering/src/main/java/StringUtils.java
src/it/resource-filtering/validate.groovy
src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java
src/test/groovy/org/asciidoctor/maven/test/AsciidoctorMojoTest.groovy
src/test/resources/src/asciidoctor/sample.ext

This PR includes the fixes discussed in issue #187.
The required libraries to enable filtering have been added and now it's possible to use it. Hovewer, this is not exposed in the documentation.
Here is the list of changes in this PR:
* Updated README to align with `maven-resource-plugin` configuration and explain the supported options. Note that using only <include> without <includes> works also, I guess it's my gradle side that preffers it.
*  Added integration test for property filtering (a.k.a. replacing). Even if it's not officially supported, that way we have an example if someone wants to use it and asks about it.
* Fixed an issue: when defining custom _file extensions_ in `sourceDocumentExtension`, these were also copied. Now they are excluded.

Resource filtering fix

---

appveyor.yml

o Download of the Maven Distribution from Maven Central instead
from the distribution Archive of Apache Software Foundation.

Fixed #242

---

pom.xml

o Do not define the execution of the maven-plugin-plugin in build
tag. Better use pluginManagement to define version and parameters,
cause the execution itself is already done by the default lifecycle
binding.

Fixed #250

---

.travis.yml

o Added configuration for cache in travis build to prevent
downloading of artifact for every build.

Fixed #246

---

README.adoc
src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java

The PR also adds better explanations for other options and puts all option configuration into a single method.
No tests are included since validation of those options require Asciidoctorj 1.6.0. When this is released, tests using Java extensions can be added.
Options are set using property names due to them not being available in OptionsBuilder.
Note, that at least, I have validated the code using an external project that uses AsciidoctorJ 1.6.0-alpha.3. Seeing 1.5.4 against 1.6.0 API has made me appreciate even more the work of Robert.

fixes #264 - adding sourcemap, catalog_assets and template_cache options

---

appveyor.yml

This PR includes:
- Cache for maven installation folder and repository. Each cache adds a depedency file (https://www.appveyor.com/docs/build-cache/#addchange-dependency), so that if that file changes the cache gets invalidated.
- Support for Java6 builds. Since officialy until asciidoctor 1.6.0 Java6 is supported and now Appveyor offers it, I added it. To make the build work for Java6, it uses maven 3.2.5 instead. Higher versions fail because they are compiled for Java7. `RefreshTest` hangs, could not reproduce, so I disabled it for Java6.
Finally, Maven wrapper has not been included to support the Java6.

Added cache control and Java6 build to appveyor

---

.travis.yml
appveyor.yml
pom.xml

As discussed https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/248, the build process have been simplified for TravisCI and Appveyor. Now the whole build & test process is done in a single execution.
2 things to mention:
- jacoco reports are only executed in Travis since this is only done to publish on coveralls.io. Other than that both build processes are equivalent.
- coveralls-maven-plugin version has been updated.

fixes #248 - Run clean verify together in CI

---

README.adoc

This PR contains:
· As a closure for https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/278 I added the resolution into the tips & trick section of the README document.
· Added brief text descriptions of the different Tips&Tricks.
· Removed Tip note about use of `revnumber` in `Passing POM properties`. I consider that the new tip is more elegant and having both can create some confusion.

Improved Tips & Tricks section with an example of header attributes

---

README.adoc
README_zh-CN.adoc

· Added note about where to find documentation for release versions  (based on https://github.com/asciidoctor/jekyll-asciidoc/)
· Added GitHub emojis for admonition icons.
Note that unlike jekyll-asciidoc, which uses branches, here I redirect to tags.

Added clarification about released documentation

---

src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java

This fixes #294 by adding an `@` symbol to the default `imagesDir`
setting. Although this default shouldn't have been there in the first
place according to @mojavelinux, at least now it is overridable from
the documents.

Allow imagesdir attribute override from documents.

---

src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java
src/test/groovy/org/asciidoctor/maven/test/AsciidoctorMojoTest.groovy

Added information about the expected source directory to the message logged if the expected directory does not exist. This could be helpful for the user.

Improved message on non-existing source directory

---

README.adoc
src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java
src/test/groovy/org/asciidoctor/maven/test/AsciidoctorMojoTest.groovy

The asciidoctor CLI allows to override the output filename with the -o, --out-file arguments. This change allows to do the same with the maven plugin.
This allows for example to include the project version in the filename:
```xml
<outputFile>my_lovely_documentation_${project.version}.pdf</outputFile>
```

added outputFile option to override the generated filename

---

src/it/maven-site-plugin/pom.xml
src/it/maven-site-plugin/src/site/asciidoc/file-with-toc.adoc
src/it/maven-site-plugin/validate.bsh
src/main/java/org/asciidoctor/maven/site/AsciidoctorParser.java

Includes:
- Replaces separator with hyphon as commented by @mojavelinux 
- Integration test to validate properties replacement with site mojo
Note: I did no include the idea of adding `pom-` as prefix. Seems excessive and overly complicated, but I am open to suggestions.

replaced '_' by '-' as maven properties separator for site mojo

---

pom.xml
src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java

* Captures the value of `project.build.sourceEncoding` and passes it to `Maven Filtering` API used to copy resources from source to target directory.
If not set, `Maven Filtering` uses the one of the OS.
* Some minor auto-format changes
**Note that** resources are not parsed, just copied, because the filtering feature is hidden. But seems reasonable to honor the property nonetheless.

If set, uses project.build.sourceEncoding for resource filtering (#305)

---

.travis.yml

*This is not a final PR, open for discussion*
This PR updates the TravisCI configuration to the new images based on Ubuntu Trusty, set as default since September (https://blog.travis-ci.com/2017-08-31-trusty-as-default-status),
The changes from TravisCI are:
- Default support only for Java8 (oracle & openjdk) and OpenJDK 7.
- Default maven version is 3.5.0
This means that:
- We no longer test against oracle 7
- **We should drop support for Java6. This I decided on my own and I'd like to hear feedback.** If we all agree, I'll update the PR removing the current hack to install it.
Thing is AsciidoctorJ no longer supports Java6, so I don't see any reason to support it on the Maven plugin. If we want to support it, some nasty hacks needs to be added to the script, similar to the ones applied …

Fix/upgrade TravisCI to trusty

---

.bundle/config

Removes old `bundler` folder. I suspect it has been there since the first releases that used the gem directly doing nothing.
PS: now that we are free of Java6 support. I'll do some maintenance in the repo, expect some silly small PRs: updating plugins, refactor tests, and other stuff.

Removed old bundler directory

---

README.adoc

- only enable toc on GitHub and in browser/editor preview
- enable font-based icons when not rendered on GitHub
- move badges down into body
- wrap paths in emphasis with path role instead of monospace
- move extra indentation in code snippet
- apply sentence per line formatting where missing
- fix some stray backticks

apply some cleanup to the README

---

src/test/groovy/org/asciidoctor/maven/test/site/AsciidoctorDoxiaParserTest.groovy
src/test/resources/src/asciidoctor/main-document.adoc
src/test/resources/src/asciidoctor/templates/block_paragraph.html.slim

This PR adds some basic unit tests to the AsciidoctorDoxiaParser class used for the `site` goal.
Validates options, attributes and templateDir processing, and defines the basic Mocks required to simulate a Maven run.
I wanted to add the testing fundations before implementation and fixing of the site goal features.

Added basic unit tests for AsciidoctorParser

---

src/it/maven-site-plugin/pom.xml
src/main/java/org/asciidoctor/maven/site/AsciidoctorDoxiaParser.java
src/test/groovy/org/asciidoctor/maven/test/site/AsciidoctorDoxiaParserTest.groovy

* Just added treatment for `baseDir` in the site plugin.
* Maven replacement DO work, added that to the integration test.
As a note to self, in case we need to apply replacements manually, can be done with `PluginParameterExpressionEvaluator`.

fixes #329 - adds treatment to allow relative baseDir on the site

---

src/main/java/org/asciidoctor/maven/AsciidoctorHelper.java
src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java
src/main/java/org/asciidoctor/maven/site/AsciidoctorDoxiaParser.java
src/test/groovy/org/asciidoctor/maven/test/site/AsciidoctorDoxiaParserTest.groovy

Just created and utility class to reuse the fix already present in the main mojo.
I have left the code unchanged but I have two notes:
1. I think that "true", "false" and Boolean could be treated together with AsciidoctorJ's `Attributes.toAsciidoctorFlag`. Imho, it makes the code more readable.
2. I don't see why this logic could not be included directly in AsciidoctorJ AttributesBuilder. Attributes class should not do anything, but the Builder purposes is to help and make configuration easier right?
/c @robertpanzer

fixes #330 - Reused attributes treatment for site goal

---

pom.xml

First - remove only parent-pom.
Next, i will add selected plugin updates from #337 
cc: @khmarbaise could You help with validation?

Remove dependency to oss-parent and copy to local pom.xml

---

src/test/groovy/org/asciidoctor/maven/test/plexus/MockPlexusContainer.groovy

Set default encoding for mock Mojo

Set default encoding to UTF-8 for resource copy plugin

---

README.adoc
src/it/rendering-single-html-with-relative-outputDirectory-and-outputFile/invoker.properties
src/it/rendering-single-html-with-relative-outputDirectory-and-outputFile/pom.xml
src/it/rendering-single-html-with-relative-outputDirectory-and-outputFile/src/main/doc/sample.asciidoc
src/it/rendering-single-html-with-relative-outputDirectory-and-outputFile/validate.groovy
src/it/rendering-single-html-with-relative-outputFile/invoker.properties
src/it/rendering-single-html-with-relative-outputFile/pom.xml
src/it/rendering-single-html-with-relative-outputFile/src/main/doc/sample.asciidoc
src/it/rendering-single-html-with-relative-outputFile/validate.groovy
src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java

The final solutions has been extremely simple.
Just use a String in the setter to keep relative path when set, otherwise maven always inserts an absolute path, rest was already implemented.
Added two integration tests and some notes to the README about `outputDirectory` and how to run tests.

fixes #348  outputFile is now relative to outputDirectory + README improvements

---

README.adoc

Adds an explanation about use of `_` to hide elements.
I added it under `sourceDirectory` because I think this is the most visible place for users.
We should probably consider reorganizing the documentation to provide much more detail in this and other areas without "bloating" the configuration section.

closes #356 : added note about use of hidden files and resources

---

appveyor.yml

Since June 18 TSL 1.0 & 1.1 are not supported by Maven Central and that causes the Java7 build to fail in AppVeyour.
Added `-Dhttps.protocols=TLSv1.2` to force use of TSL v1.2 and a note to remind us to remove it once we don't support Java7.

Added TSLv1.2 flag to appveyor build

---

pom.xml
src/it/maven-site-plugin/pom.xml

Added a workarround (not proud of it) to ensure it-tests work fine with maven-site-plugin 3.4.
Note that normal site runs, don't need this. Only for It-tests

Fix maven-site it test + update enforcer plugin

---

src/it/thread-safe/asciidoctor-project-1/pom.xml
src/it/thread-safe/asciidoctor-project-1/src/main/doc/sample.asciidoc
src/it/thread-safe/asciidoctor-project-2/pom.xml
src/it/thread-safe/asciidoctor-project-2/src/main/doc/sample.asciidoc
src/it/thread-safe/asciidoctor-project-3/pom.xml
src/it/thread-safe/asciidoctor-project-3/src/main/doc/sample.asciidoc
src/it/thread-safe/invoker.properties
src/it/thread-safe/pom.xml
src/it/thread-safe/validate.groovy
src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java

This annotation will remove a maven build warning.
Resolves: #326

Mark BuildMojo as threadSafe

---

README.adoc
pom.xml
src/it/spi-registered-log/asciidoctor-project/pom.xml
src/it/spi-registered-log/asciidoctor-project/src/main/doc/sample.asciidoc
src/it/spi-registered-log/invoker.properties
src/it/spi-registered-log/log-handler/pom.xml
src/it/spi-registered-log/log-handler/src/main/java/org/asciidoctor/maven/test/TestLogHandlerService.java
src/it/spi-registered-log/log-handler/src/main/resources/META-INF/services/_org.asciidoctor.extension.spi.ExtensionRegistry
src/it/spi-registered-log/log-handler/src/main/resources/META-INF/services/org.asciidoctor.log.LogHandler
src/it/spi-registered-log/pom.xml
src/it/spi-registered-log/validate.groovy
src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java
src/main/java/org/asciidoctor/maven/log/FailIf.java
src/main/java/org/asciidoctor/maven/log/LogHandler.java
src/main/java/org/asciidoctor/maven/log/LogRecordHelper.java
src/main/java/org/asciidoctor/maven/log/MemoryLogHandler.java
src/test/groovy/org/asciidoctor/maven/test/AsciidoctorHttpMojoTest.groovy
src/test/groovy/org/asciidoctor/maven/test/AsciidoctorMojoExtensionsTest.groovy
src/test/groovy/org/asciidoctor/maven/test/AsciidoctorMojoLogHandlerTest.groovy
src/test/groovy/org/asciidoctor/maven/test/AsciidoctorMojoTest.groovy
src/test/groovy/org/asciidoctor/maven/test/AsciidoctorRefreshMojoTest.groovy
src/test/groovy/org/asciidoctor/maven/test/AsciidoctorZipMojoTest.groovy
src/test/groovy/org/asciidoctor/maven/test/plexus/MockPlexusContainer.groovy
src/test/java/org/asciidoctor/maven/test/processors/ManpageInlineMacroProcessor.java
src/test/resources/src/asciidoctor/errors/document-with-missing-include.adoc

Addresses: https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/261, https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/178
_Features are complete, but there's an issue with duplicated asciidoctor messages https://github.com/asciidoctor/asciidoctorj/issues/669._ Depending on suggestions we can merge or review the feature.
**Feature summary**
This PR adds a new configuration element as follows:
```xml
<logHandler>
<outputToConsole>true</outputToConsole>
<failIf>
<severity>WARNING</severity>
<containsText>super-important-document.adoc</containsText>
</failIf>
</logHandler>
```
* `outputToConsole`: redirects asciidoctor messages to maven's logger. Messages are shown as Maven's INFO during renderitzation. Messages will appear twice as mentioned in issue …

Added new feature to fail based on different conditions

---

src/it/spi-registered-log/asciidoctor-project/src/main/doc/sample.asciidoc
src/it/spi-registered-log/log-handler/src/main/java/org/asciidoctor/maven/test/TestLogHandlerService.java
src/it/spi-registered-log/validate.groovy
src/main/java/org/asciidoctor/maven/log/LogRecordHelper.java
src/test/groovy/org/asciidoctor/maven/test/AsciidoctorMojoLogHandlerTest.groovy
src/test/resources/src/asciidoctor/errors/document-with-invalid-reference.adoc

Adds a null check to the cursor of logRecords.
In case the message does not have a cursor, it will print a message without it following Asciidoctor current format.
Example:
`[info] asciidoctor: WARN: invalid reference: section-id`

closes #366 Control when cursor in logger is null

---

.travis.yml
pom.xml

`maven-surefire-plugin` has been updated also as a requeriment.
NOTE:
Java 11 fails during a test due to ssl changes, see below. I will deal with it in another PR.
```[ERROR] github files can be included(org.asciidoctor.maven.test.AsciidoctorMojoTest)  Time elapsed: 4.802 s  <<< ERROR!
org.asciidoctor.internal.AsciidoctorCoreException: org.jruby.exceptions.RaiseException: (LoadError) load error: jopenssl/load -- java.lang.StringIndexOutOfBoundsException: begin 0, end 3, length 2
at org.asciidoctor.maven.test.AsciidoctorMojoTest.github files can be included(AsciidoctorMojoTest.groovy:990)
Caused by: org.jruby.exceptions.RaiseException: (LoadError) load error: jopenssl/load -- java.lang.StringIndexOutOfBoundsException: begin 0, end 3, length 2
```

Added openjdk9 and Java 10 to TravisCI

---

src/main/java/org/asciidoctor/maven/AsciidoctorHttpMojo.java
src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java

The methods `Asciidoctor.render*()` are on the way of being deprecated (see asciidoctor/asciidoctorj#711)
Therefore this PR changes the calls to Asciidoctor to use the corresponding `convertFile()` method.

Use asciidoctor.convertFile() instead of asciidoctor.renderFile()

---

.travis.yml

As mentioned here: https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
Travis is disabling docker model.
This PR just removes configurations that not necessary or working:
* removes `sudo: false`
* removes `dist: trusty`, which is not needed since trusty is already default

Update TravisCI setting to new vm based builds

---

README.adoc
pom.xml
src/it/spi-registered-log/asciidoctor-project/src/main/doc/sample.asciidoc
src/it/spi-registered-log/validate.groovy
src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java
src/main/resources/enable_verbose.rb
src/test/groovy/org/asciidoctor/maven/test/AsciidoctorMojoLogHandlerTest.groovy

This updates AsciidoctorJ version and tests that started failing due to https://github.com/asciidoctor/asciidoctor/issues/2722.
@mojavelinux I added about the issue in the README. I'd appreciate your opinion on wether we should make this visible or not.

Update asciidoctorj to 1.5.8.1

---

README.adoc

This is a trick that has come up lately a few times and I think it is noteworthy enough to add it to the _Tips & Tricks_ section of the README

Add tip on how to show the asciidoctor version

---

src/test/resources/src/asciidoctor/github-include.adoc

This PR fixes a test that started failing due a change in a remote file being used.

use comet branch name for remote include test instead of master

---

.travis.yml
appveyor.yml
pom.xml
src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java
src/main/java/org/asciidoctor/maven/log/MemoryLogHandler.java
src/test/groovy/org/asciidoctor/maven/test/AsciidoctorMojoLogHandlerTest.groovy
src/test/groovy/org/asciidoctor/maven/test/AsciidoctorMojoTest.groovy
src/test/java/org/asciidoctor/maven/test/processors/AutoregisteredProcessor.java
src/test/java/org/asciidoctor/maven/test/processors/ChangeAttributeValuePreprocessor.java
src/test/java/org/asciidoctor/maven/test/processors/FailingPreprocessor.java
src/test/java/org/asciidoctor/maven/test/processors/GistBlockMacroProcessor.java
src/test/java/org/asciidoctor/maven/test/processors/ManpageInlineMacroProcessor.java
src/test/java/org/asciidoctor/maven/test/processors/RequireCheckerTreeprocessor.java
src/test/java/org/asciidoctor/maven/test/processors/UriIncludeProcessor.java
src/test/java/org/asciidoctor/maven/test/processors/YellBlockProcessor.java
src/test/resources/src/asciidoctor/github-include.adoc

This PR makes the required changes to upgrade the plugin to AsciidoctorJ 2.0.0-RC.1
Notable changes are:
* Minimum required version of Java is now Java 8
* I ignored the tests for the warnings for invalid refs, I also have them commented in AsciidoctorJ
There's one test failing locally for me right now, which expects rendering with the Pygments highlighter to fail, however that succeeds.
I am unclear right now if this is now the expected behavior or if this is coming from my local machine setup, even though I don't have pygments installed locally afaict.

Upgrade to AsciidoctorJ 2.0.0-RC.1

---

README.adoc
README_zh-CN.adoc
src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java
src/test/groovy/org/asciidoctor/maven/test/AsciidoctorMojoTest.groovy

This PR:
* Removes the deprecated option "templateDir". Uses should use "templateDirs" instead.
* Updates tests accordingly
* Updates READMEs accordingly

closes #265: removes deprecated templateDir option

---

README_zh-CN.adoc

I missed this change in https://github.com/asciidoctor/asciidoctor-maven-plugin/pull/428.

fixes default value for backend in Chinese readme

---

README.adoc
pom.xml
src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java
src/main/java/org/asciidoctor/maven/log/AsciidoctorConvertionException.java
src/main/java/org/asciidoctor/maven/log/LogHandler.java
src/main/java/org/asciidoctor/maven/log/LogRecordHelper.java
src/main/java/org/asciidoctor/maven/log/LogRecordsProcessors.java
src/main/java/org/asciidoctor/maven/log/MemoryLogHandler.java
src/main/java/org/asciidoctor/maven/site/AsciidoctorDoxiaParser.java
src/main/java/org/asciidoctor/maven/site/SiteConversionConfiguration.java
src/main/java/org/asciidoctor/maven/site/SiteConversionConfigurationParser.java
src/main/java/org/asciidoctor/maven/site/SiteLogHandlerDeserializer.java
src/test/groovy/org/asciidoctor/maven/test/site/AsciidoctorDoxiaParserTest.groovy
src/test/java/org/asciidoctor/maven/log/LogRecordHelperTest.java
src/test/java/org/asciidoctor/maven/site/SiteConversionConfigurationParserTest.java
src/test/java/org/asciidoctor/maven/site/SiteLogHandlerDeserializerTest.java
src/test/java/org/asciidoctor/maven/site/Xpp3DoomBuilder.java

Closes #400 
This PR adds the possibility to add "logHandler" options to abort a site generation based on certain conditions (e.g. some warning messages are detected).
This PR:
* Adds `SiteConversionConfigurationParser` and `SiteLogHandlerDeserializer` to help reading site configurations.
* Removes support for `templateDir`, users should use `templateDirs`.
* Refactors log processing logic into `LogRecordsProcessors` to be reused between Mojos and site module. As a note, it has some "nasty" code due to the fact that Doxia and Mojos use different logging interfaces and return different exceptions. I am happy with this for now. In deeper refactors this can be reviewed.
* Updates README with logHandler explanation and some additional reviews.
It also includes:
* Update of …

Support log handler configuration for site generation

---

README.adoc
src/main/java/org/asciidoctor/maven/AsciidoctorHttpMojo.java
src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java
src/main/java/org/asciidoctor/maven/AsciidoctorRefreshMojo.java
src/main/java/org/asciidoctor/maven/log/AsciidoctorConversionException.java
src/main/java/org/asciidoctor/maven/log/LogRecordsProcessors.java
src/test/groovy/org/asciidoctor/maven/test/AsciidoctorHttpMojoTest.groovy
src/test/groovy/org/asciidoctor/maven/test/AsciidoctorMojoExtensionsTest.groovy
src/test/groovy/org/asciidoctor/maven/test/AsciidoctorMojoLogHandlerTest.groovy
src/test/groovy/org/asciidoctor/maven/test/AsciidoctorMojoTest.groovy
src/test/groovy/org/asciidoctor/maven/test/AsciidoctorRefreshMojoTest.groovy
src/test/groovy/org/asciidoctor/maven/test/site/AsciidoctorDoxiaParserTest.groovy
src/test/java/org/asciidoctor/maven/test/processors/RequireCheckerTreeprocessor.java
src/test/resources/src/asciidoctor/relative-path-treatment/_this_is_ignored/ignored.adoc
src/test/resources/src/asciidoctor/relative-path-treatment/level-1-1/level-2-2/_this_is_ignored/ignored.adoc

To align with Asciidoctor convenvtions and teminology replaces uses of the word "render" by "convert" in documentation and code.
Additionally include some minnor fixed to the README.

closes #376: replaces use of word render by convert in README and code

---

README.adoc
src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java

This PR:
* Removes the unused `title` option found in the Mojo. Since we never got this reported I assume this won't be missed, plus it never got reported. The intended feature can be obtaine setting `<doctitle>` in the attributes block.
* Updated the README: for that the section "Build-in attributes" has been removed. To me it makes no sense since having duplicate configurations for attributes (while adds automatic completion) makes manteinance more complicated and is prone to cause confusion in users. As discused in 2.0.0 roadmap.
* Also a couple of minnor fixes in the readme

closes #437: removes unused title option from mojo + updates README

---

README.adoc
src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java
src/test/groovy/org/asciidoctor/maven/test/AsciidoctorMojoTest.groovy

This PR:
* Removes the attributeMissing option to be used in as a normal attribute. current solution had moreover the limitation of not being able to set "warn" as value. I updated the test, though one could argue these are not integration tests and should not be there.
* Also, added an exaplanation of how to combine the attribute with logHandler to fail a build on missing attibutes to "tips & tricks"

closes #417: removes attributeMissing option in favour of attributes configuration

---

src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java
src/test/groovy/org/asciidoctor/maven/test/AsciidoctorMojoTest.groovy

This is the last attribute that was still configurable as an option directly in the mojo.

remove attributeUndefined option in favour of direct atrtibute usage

---

CHANGELOG.adoc
pom.xml

This PR:
* Updates `maven-release-plugin` version to latests 3.0.0-M1. I have run several tests and haven't found issues for our project.
* Sets default value for scm.tag element. The plugin will create it if not found but with bad formatting, setting it we avoid any problem. The value is properly updated in the tags with the tag name.
Also, updated my notes with a new simplified process with less human intervention and better rollback procedure: https://github.com/abelsromero/asciidoctor-maven-plugin/wiki/Maven-release-steps

updates maven-release-plugin version to latests 3.0.0-M1 and set scm.tag with new defaults

---

CHANGELOG.adoc
src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java

This PR fixes Maven dependencies used in AsciidoctorMojo appearing in the plugin descriptor as parameters.
Components like the MavenProject or MavenSession used internally and injectes by Plexus appeared as parameters becase we uses @Parameter annotation for injection. This could cause confusion in IDEs offering autocompletion.
This PR replaces it with @Inject so this components are injected but they do not appear.
NOTE: Inject has been used intead od Plexus @Component or @Required for being more standard. But they all work the same in this case.

removes Maven required components from plugin descriptor using correct CI annotation

---

.github/workflows/ci-build.yaml
.travis.yml
CHANGELOG.adoc

There's a temporal issue with coveralls.io, in the meantime I am removing it. We will still need to rely on Travis for that.

fix GitHub Actions configuration

---

CHANGELOG.adoc
README.adoc
src/it/inject-attributes-from-maven-pom/invoker.properties
src/it/inject-attributes-from-maven-pom/pom.xml
src/it/inject-attributes-from-maven-pom/src/docs/asciidoc/attributes-example.adoc
src/it/inject-attributes-from-maven-pom/validate.groovy
src/main/java/org/asciidoctor/maven/AsciidoctorHelper.java
src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java
src/main/java/org/asciidoctor/maven/site/SiteConversionConfigurationParser.java
src/test/groovy/org/asciidoctor/maven/test/AsciidoctorMojoTest.groovy
src/test/groovy/org/asciidoctor/maven/test/plexus/MockPlexusContainer.groovy
src/test/resources/src/asciidoctor/attributes-example.adoc

This PR automatically injects maven properties as attributes (replacing . by -).
This feature is already present in the site integration, so it makes sense to apply it here.
This PR contains:
* Implementation resing same code as site module
* Unit test
* IT test
* Updated README. We could remove a section to make things simpler now

Inject maven properties in asciidoctor mojo

---

.github/workflows/build.yaml
pom.xml

This PR:
* Fixes configuration to push coverall.io resuls from GH Actions build pipeline. Thanks to @mojavelinux for setting up the repo.
This is restricted to only the linux, Java11 build for no special reason other than this is the more similar to production environments.
* Applies fix to `coveralls-maven-plugin` to run on Java11.

fix coveralls.io setup to run on GH actions

---

.travis.yml
CHANGELOG.adoc
appveyor.yml

This PR simplifies CI configuration:
* Travis only runs for Java11 to enable easy integration of coveralls.io
* Appveyor is still kep but limited to java 8 and 11. Also upgraded maven version.

simplify TravisCI for coveralls and Appveyor setup to Java8,11

---

CHANGELOG.adoc
src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java
src/main/java/org/asciidoctor/maven/Synchronization.java
src/main/java/org/asciidoctor/maven/extensions/ExtensionConfiguration.java

As part of some clean up tasks, this PR:
* Removes unnecessary `org.apache.maven.plugins.annotations.Parameter` usages in ExtensionConfiguration, Synchronization and Resources, and in AsciidoctorMojo.
This is because properties in beans cannot be configured via terminal with _-D_. I'll do more search while the PR is open, but could not find any official doc so far and tests where unsuccessful. Note that List of String or File can be assigned passing a comma separated list like `mvn -Dasciidoctor.requires=onegem,anothergem`

removes unnecessary @Parameter configuration from ExtensionConfiguration, Synchronization and Resources

---

CHANGELOG.adoc
src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java
src/test/groovy/org/asciidoctor/maven/test/plexus/MockPlexusContainer.groovy

Part of cleanup tasks, this PR:
* Removes the unused `org.sonatype.plexus.build.incremental.BuildContext` from AsciidoctorMojo.

removes unused maven BuildContext in AsciidoctorMojo

---

CHANGELOG.adoc
src/it/convert-with-minimal-configuration/invoker.properties
src/it/convert-with-minimal-configuration/pom.xml
src/it/convert-with-minimal-configuration/src/docs/asciidoc/sample.asciidoc
src/it/convert-with-minimal-configuration/validate.groovy
src/main/java/org/asciidoctor/maven/AsciidoctorHttpMojo.java
src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java
src/main/java/org/asciidoctor/maven/AsciidoctorRefreshMojo.java

Part of clean up tasks, this PR:
* Removes unnecessary `required = false` from mojo parameters, since this is the default value.
* Removes incorrect `required = true` from `sourceDirectory` and `outputDirectory`. This was incorrect since these parameters have default values. Added an IT test to assert this behauviour.

removes unnecessary required configuration from mojo parameters

---

src/test/groovy/org/asciidoctor/maven/test/AsciidoctorHttpMojoTest.groovy
src/test/groovy/org/asciidoctor/maven/test/AsciidoctorMojoExtensionsTest.groovy
src/test/groovy/org/asciidoctor/maven/test/AsciidoctorMojoLogHandlerTest.groovy
src/test/groovy/org/asciidoctor/maven/test/AsciidoctorMojoTest.groovy
src/test/groovy/org/asciidoctor/maven/test/AsciidoctorMojoTestHelper.groovy
src/test/groovy/org/asciidoctor/maven/test/AsciidoctorRefreshMojoTest.groovy

Another clean up PR. This PR:
* Creates AsciidoctorMojoTestHelper::newOutputTestDirectory to create a random single output directory for each test. May seem unimportant, but this allowed to detect a false positive in the current tests and makes diagnostic easier.
Since it's a test refactor, not worth mentioning in CHANGELOG
NOTE: Since zip mojo is decrecated test have not been modified.

unifies tests outputs into single directory structure

---

CHANGELOG.adoc
src/main/java/org/asciidoctor/maven/AsciidoctorHttpMojo.java
src/main/java/org/asciidoctor/maven/AsciidoctorRefreshMojo.java

This PR fixes an issue by ensuring source are converted 1 each.
Also includes a couple of minnor formatting changes.

fixes #467 - prevent files from being converted twice in http mojo

---

src/main/java/org/asciidoctor/maven/AsciidoctorHttpMojo.java
src/main/java/org/asciidoctor/maven/AsciidoctorRefreshMojo.java

Small fix, this PR:
* Corrects http configuration which was in refresh mojo placing it in the http mojo.
Since both mojo's are still not public, not worth mentioning in changelog.

moves port configuration from refresh to http mojo

---

src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java
src/main/java/org/asciidoctor/maven/AsciidoctorRefreshMojo.java
src/main/java/org/asciidoctor/maven/process/AsciidoctorHelper.java
src/main/java/org/asciidoctor/maven/process/CustomExtensionDirectoryWalker.java
src/main/java/org/asciidoctor/maven/process/SourceDirectoryFinder.java
src/main/java/org/asciidoctor/maven/site/SiteConversionConfigurationParser.java
src/test/groovy/org/asciidoctor/maven/test/AsciidoctorMojoTest.groovy
src/test/java/org/asciidoctor/maven/SourceDirectoryFinderTest.java
src/test/java/org/asciidoctor/maven/process/CustomExtensionDirectoryWalkerTest.java
src/test/resources/src/asciidoctor/relative-path-treatment/level-1-1/_internal-partial.adoc

Related to #472 
The original approach was to re-use logic from `AsciidoctorMojo`, however that was not efficient in that required creating multiple file monitors/listeners. Finally, I opted to apply custom logic that replicates under-the-hood the same logic to monitor sources, the only missing piece was taking into account custom file extensions.
In sum, this PR:
* Make `auto-refresh` mojo take `sourceDocumentExtensions` into consideration when filtering sources.
* Created `process` package to group classes used to assist in the conversion process of different mojos.
In future refactors if these become generic classes with no Maven dependencies may end up outside of the `maven` package. Maybe even sub-module? The case for a sub-module deppends more in how this affects mavenCentral …

fixes auto-refresh mojo not taking into account customized file extension

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.adoc

This PR adds GitHub templates for PR and Issues.
I have based them on [asciidoctorj](https://github.com/asciidoctor/asciidoctorj/tree/master/.github) and [asciidoctor-intellij-plugin](https://github.com/asciidoctor/asciidoctor-intellij-plugin/tree/master/.github).
My approach have been to help people reporting more than mantainers. So I applied thess approaches:
* Simple structure
* Welcoming messages and texts
* Ask for minimal requirements
* Avoid "pedantic" remarks like requiring tests, docs or asking that the full builld completes.

Adds GitHub PR and issue templates

---

CHANGELOG.adoc
src/main/java/org/asciidoctor/maven/AsciidoctorHttpMojo.java
src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java
src/main/java/org/asciidoctor/maven/AsciidoctorRefreshMojo.java
src/main/java/org/asciidoctor/maven/refresh/AbstractFileAlterationListenerAdaptor.java
src/main/java/org/asciidoctor/maven/refresh/AsciidoctorConverterFileAlterationListenerAdaptor.java
src/main/java/org/asciidoctor/maven/refresh/ResourceCopyFileAlterationListenerAdaptor.java
src/main/java/org/asciidoctor/maven/refresh/TimeCounter.java
src/test/groovy/org/asciidoctor/maven/test/AsciidoctorHttpMojoTest.groovy
src/test/java/org/asciidoctor/maven/AsciidoctorRefreshMojoTest.java
src/test/java/org/asciidoctor/maven/io/ConsoleHolder.java
src/test/java/org/asciidoctor/maven/io/StringsCollectionsInputStream.java
src/test/java/org/asciidoctor/maven/refresh/ResourceCopyFileAlterationListenerAdaptorTest.java

Adds efficient synchronization of resources for refresh mojo.
`*FileAlterationListenerAdaptor` hierarchy has some duplication but its a tradeoff I think is worth. The other alterntive is making some complex solutions with several lambdas or create abstract methods to customize log messages.
Closes #472

Adds synchronization of resources for refresh mojo

---

CHANGELOG.adoc
README.adoc

`auto-refresh` mojo has been a hidden feature for years. This PR makes it public and fully supported adding it to the README.
PS: I am considering changing the name to "refresh-asciidoc" as analogy to "process-asciidoc". If no objections are found.

adds explanation of auto-refresh mojo to README

---

CHANGELOG.adoc
src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java
src/main/java/org/asciidoctor/maven/AsciidoctorRefreshMojo.java
src/main/java/org/asciidoctor/maven/io/AsciidoctorFileScanner.java
src/main/java/org/asciidoctor/maven/refresh/ResourcesPatternBuilder.java
src/test/java/org/asciidoctor/maven/AsciidoctorRefreshMojoTest.java
src/test/java/org/asciidoctor/maven/io/TestFilesHelper.java
src/test/java/org/asciidoctor/maven/refresh/ResourceCopyFileAlterationListenerAdaptorTest.java
src/test/java/org/asciidoctor/maven/refresh/ResourcesPatternBuilderTest.java

Replicates the logic from `process-asciidoc` mojo that prevents docInfo files from being copied into the output directory.
Following previous pattern, files that are not required in output ar filtered by `ResourceCopyFileAlterationListenerAdaptor` using a filename regular expression.
To make the pattern easier to mantain the logic has been extracted into a class `ResourcesPatternBuilder` with proper unit tests for it.
Also includes:
- Moved all constants related …

avoids docInfo files from being copied in refresh mojo

---

CHANGELOG.adoc
pom.xml
src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java

Originally `maven-javadoc-plugin` version configuration, using the version defined in `<pluginManagement>`.
But also upgrades the version to latest v3.2.0.
Given the plugin is used only once, could define it explicitely.
But for consistency I'd rather have all maven plugin version defined togetherd under pluginManagement.
No.

bumps maven-javadoc-plugin to latest 3.2.0

---

CHANGELOG.adoc
README.adoc
src/main/java/org/asciidoctor/maven/AsciidoctorHttpMojo.java
src/main/java/org/asciidoctor/maven/AsciidoctorMaven.java
src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java
src/main/java/org/asciidoctor/maven/AsciidoctorRefreshMojo.java
src/main/java/org/asciidoctor/maven/AsciidoctorZipMojo.java
src/main/java/org/asciidoctor/maven/http/AsciidoctorHandler.java
src/main/java/org/asciidoctor/maven/http/AsciidoctorHttpServer.java
src/main/java/org/asciidoctor/maven/io/Zips.java
src/main/java/org/asciidoctor/maven/process/AsciidoctorHelper.java
src/main/java/org/asciidoctor/maven/site/AsciidoctorDoxiaParser.java
src/main/java/org/asciidoctor/maven/site/AsciidoctorDoxiaParserModule.java

- [] Feature
~Add & automate copyright to all source files.~
Original intention changed as per discusion below, now:
* Add copyright notice to readme.
* Remove unnecessary licence headers. All those that comply with license set at project level.
~First, there's al anternative plugin (https://www.mojohaus.org/license-maven-plugin) but I found it seems less mantained.
Secondly, the year could be automated using `<maven.build.timestamp.format>yyyy</maven.build.timestamp.format>`, but I am afraid of possible side effects during release.~
No
**Are …

automates application of licence header to source files with license-maven-plugin

---

CHANGELOG.adoc
README.adoc
src/main/java/org/asciidoctor/maven/AsciidoctorHttpMojo.java
src/main/java/org/asciidoctor/maven/AsciidoctorRefreshMojo.java
src/main/java/org/asciidoctor/maven/http/AsciidoctorHandler.java
src/main/java/org/asciidoctor/maven/http/AsciidoctorHttpServer.java
src/test/groovy/org/asciidoctor/maven/test/AsciidoctorHttpMojoTest.groovy
src/test/java/org/asciidoctor/maven/http/AsciidoctorHttpServerTest.java

Adds official support to the `http` mojo that offers life refresh + http publication.
Yes, as explainen in issue https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/468.
Documentation is becoming convoluted. After release we need to consider building some site with antora.
I have become disenchanted with maven internals, and I don't consider a normal maven site a good option.
*Finally, please add a corresponding …

closes #468: adds first life refresh in http mojo

---

README.adoc

Set the `uri-licence` attribute in README so the link in preview works.
No

Fix uri-license in README

---

CHANGELOG.adoc
docs/modules/plugin/partials/process-asciidoc-mojo-parameters.adoc
docs/modules/site-integration/pages/index.adoc

Improve docs about usage of Maven properties.
Now it should be more clear that now only properties set in the pom are passed as attributes.
Explanation could be extended to explicitely state that Maven Model are NOT set. But for now I'd like to keep it simple.
Also, the text is duplu
Need to refresh general docs site.

Remove ambiguity in usage of maven properties docs

---

CHANGELOG.adoc
docs/modules/plugin/partials/process-asciidoc-mojo-parameters.adoc

Add an ID to the attributes description on the mojos so it can be directly referenced by URL.
More specifically, this is so we can do a redirect to sections that no longer exists and which content is found in the attributes description in https://asciidoctor.org/docs/. Similar to https://github.com/asciidoctor/asciidoctor.org/pull/995.
Not that I know of.
Docs in docs.asciidoctor.org/ need to be rebuild.
*Finally, please add a …

Add ID to 'attributes' to be able to generate direct url from other docs

---

CHANGELOG.adoc
pom.xml
src/test/java/org/asciidoctor/maven/AsciidoctorHttpMojoTest.java
src/test/java/org/asciidoctor/maven/AsciidoctorIntegrationTest.java
src/test/java/org/asciidoctor/maven/AsciidoctorMojoExtensionsTest.java
src/test/java/org/asciidoctor/maven/AsciidoctorMojoLogHandlerTest.java
src/test/java/org/asciidoctor/maven/AsciidoctorMojoTest.java
src/test/java/org/asciidoctor/maven/AsciidoctorRefreshMojoTest.java
src/test/java/org/asciidoctor/maven/AsciidoctorZipMojoTest.java
src/test/java/org/asciidoctor/maven/SourceDirectoryFinderTest.java
src/test/java/org/asciidoctor/maven/http/AsciidoctorHttpServerTest.java
src/test/java/org/asciidoctor/maven/log/LogRecordHelperTest.java
src/test/java/org/asciidoctor/maven/process/CustomExtensionDirectoryWalkerTest.java
src/test/java/org/asciidoctor/maven/refresh/ResourceCopyFileAlterationListenerAdaptorTest.java
src/test/java/org/asciidoctor/maven/refresh/ResourcesPatternBuilderTest.java
src/test/java/org/asciidoctor/maven/site/AsciidoctorDoxiaParserTest.java
src/test/java/org/asciidoctor/maven/site/SiteConversionConfigurationParserTest.java
src/test/java/org/asciidoctor/maven/site/SiteLogHandlerDeserializerTest.java
src/test/java/org/asciidoctor/maven/test/processors/RequireCheckerTreeprocessor.java

Upgrade tests from JUnit 4 to Junit 5.
No.
No. Just need to validate tests run normally and coverage is reported.

Upgradte tests to JUnit5

---

CHANGELOG.adoc
docs/modules/plugin/partials/process-asciidoc-mojo-parameters.adoc

Improve documentation
I don't think this warrants a changelog entry.

Fix broken links to extension api documentation

---

.mvn/wrapper/maven-wrapper.properties
CHANGELOG.adoc
pom.xml

* Upgrade maven wrapper to use latest Maven v3.8.1 wich contains security fixes https://maven.apache.org/docs/3.8.1/release-notes.html.
It also:
* Bumps maven-compiler-plugin to v3.8.1
* Bumps jacoco-maven-plugin to 0.8.6
* Bumps maven-filtering to 3.2.0
No
No

Set maven wrapper to use maven v3.8.1

---

CHANGELOG.adoc
pom.xml
src/test/java/org/asciidoctor/maven/AsciidoctorIntegrationTest.java

Upgrade to latest Asciidoctorj version 2.4.3.
No
Also upgrade jruby aligned to Asciidoctorj.

Bump Asciidoctorj to v2.4.3 and jRuby to v9.2.14.0

---

pom.xml
src/main/java/org/asciidoctor/maven/site/SiteConversionConfigurationParser.java

Removed because security alerts with commons-io:2.5 and
that the actual versions are out of our control because
they are provided by Maven runtime.
Reduce maintenance efforts on dependencies that are actually out of our control.
Both `commons-io` and `commons-lang3` are provided by Maven runtime, so even if we override for a newer versions we will still use the one in Maven.
So, it's better to just use the version provided.
No that I am aware.
The initial motivation …

Remove apache commons direct dependencies

---

pom.xml

Add reference to organization to pom. That way uses using it can get more insight of the community and a reference to the page.
It could be argued we could set url to docs.asciidoctor.org, but I think the current one is nicer for a first impressio and the docs under "Docs" option already point to docs.asciidoctor.org.
Not in terms of actual features.
Fixes #537

Add 'Asciidoctor' organization to pom.xml

---

pom.xml

Bump versions of maven plugins related to build tasks:
* maven-source-plugin to v3.2.1
* maven-javadoc-plugin to v3.3.0
* maven-jar-plugin to v3.2.0
* maven-invoker-plugin to v3.2.2
* maven-gpg-plugin to v3.0.1i
* Enable signature name for gpg
* Fix 'http' references in pom
no
no
Not worth mentioning.

Bump build plugins versions

---

.github/workflows/build.yaml
CHANGELOG.adoc
docs/modules/plugin/partials/auto-refresh-mojo-parameters.adoc
src/main/java/org/asciidoctor/maven/AsciidoctorRefreshMojo.java
src/main/java/org/asciidoctor/maven/process/SourceDocumentFinder.java
src/main/java/org/asciidoctor/maven/refresh/AdditionalSourceFileAlterationListenerAdaptor.java
src/test/java/org/asciidoctor/maven/AsciidoctorRefreshMojoTest.java

Fix conversion not happending when included sources where modified in `autp-refresh` and `http` mojo.
As discussed in #403 at the end we added a new option available for those mojos to allow users to specify other files to "listen to changes on". On a change or creation, a full rebuild will be done.
Current  approach allows users to specify a set of extra sources to monitor.
On change a full rebuild (without copying resources) will happen. A full rebuild is necessary since we don't know which sources are affected.
**Are there any implications …

Allow setting included sources to run full refresh on change

---

CHANGELOG.adoc
src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java
src/main/java/org/asciidoctor/maven/process/SourceDocumentFinder.java
src/test/java/org/asciidoctor/maven/process/SourceDocumentFinderTest.java
src/test/resources/src/asciidoctor/source-finder/_enclosing/src/simple.adoc

Fix sources not being included when enclosing path started with `_`.
That is some directory in the upper path containing the project had the hidden preffix.
The fix is simply checking for paths ONLY in the project path.
No.
Did some formatting and minnor refactors.
Sicne it's first PR after a release, also opens new unreleased section in CHANGELOG.
Fixes #545 

Fix excluding sources when enclosing parent path starts with _

---

CHANGELOG.adoc
README.adoc
docs/antora.yml

Update metadata for 2.2.1 release.
A minor release is done to fix #545 issue which affects Jenkins users.
n/a
n/a

Prepare 2.2.1 release

---

CHANGELOG.adoc
docs/modules/plugin/partials/auto-refresh-mojo-parameters.adoc
docs/modules/plugin/partials/http-mojo-parameters.adoc
docs/modules/plugin/partials/process-asciidoc-mojo-parameters.adoc
docs/modules/site-integration/pages/index.adoc

Fixes #533
**Are there any alternative ways to implement this?** 
no, but we can discuss how to define the id's for the anchors 
no

Add anchor to configuration options in documentation

---

CHANGELOG.adoc
src/main/java/org/asciidoctor/maven/io/AsciidoctorFileScanner.java
src/main/java/org/asciidoctor/maven/process/SourceDocumentFinder.java
src/test/java/org/asciidoctor/maven/AsciidoctorMojoTest.java
src/test/java/org/asciidoctor/maven/process/SourceDocumentFinderTest.java
src/test/resources/src/asciidoctor/relative-path-treatment/.these_sources_are_not_processed/ignored.adoc
src/test/resources/src/asciidoctor/relative-path-treatment/level-1-1/.internal-dot-partial.adoc

Seeing the recent light of an issue with internal files treatment #545 we have been able to spot similar issues with treatment of hidden (prefix "." files and directories).
For that reason I think it's reasonable the next changes:
- FIX: In v2.1.0 sources inside a hidden directory where not processed, but they are in 2.2.x
- FEATURE CHANGE: While in v2.1.0 resources folders with "." where copied, it's not consistent with sources and internal resources ("_"). So this PR applies same treatment as with "_" and aligns it with "." sources which are also ignored.
**Are there any alternative ways to …

Treat dot files and folders same as internal

---

CHANGELOG.adoc
pom.xml

Update netty dependency used for life preview of refresh mojos and fix possible CVS.
n/a
No, test pass and not feature is added or changes.

Bump netty-codec-http to v4.1.71.Final

---

CHANGELOG.adoc
src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java
src/main/java/org/asciidoctor/maven/log/LogRecordFormatter.java
src/main/java/org/asciidoctor/maven/log/LogRecordsProcessors.java
src/main/java/org/asciidoctor/maven/site/AsciidoctorDoxiaParser.java
src/test/java/org/asciidoctor/maven/log/LogRecordFormatterTest.java

Validates if the cursor file path is contained in the configured source directory of the plugin to avoid crashing.
It also checks if the cursor is a remote url to prevent similar crash.
The subpath and http validations could be done with java.io.Path but required methods are not available in Java8. This can be refactored with we drop compat for Java8 in v3.0.0.
No.

Avoid crash when processing logs of files not under the source dir

---

CHANGELOG.adoc
pom.xml
src/it/maven-site-plugin/pom.xml
src/main/java/org/asciidoctor/maven/site/AsciidoctorDoxiaParser.java

Fixes #564 
* Make AsciidoctorDoxiaParser extend AbstractTextParser instad of XhtmlParser
* Bump minimum Doxia version to v1.10
The issue does not appear when overriding `doxia-core` v1.11.1 with v1.9.1, so it could be there's some other issue on doxia.
However, it is also true `AsciidoctorDoxiaParser` extended `XhtmlParser` which makes no sense and which is consistent with the error that points to invalid XML document (of course AsciiDoc is not XML compatible).
* Minimum supported version for doxia-core is v1.10 now (to be sure maven-site-plugin …

Fix site integration failing with maven-site-plugin v3.10.0

---

.github/workflows/build.yaml
CHANGELOG.adoc
docs/antora.yml
docs/modules/ROOT/pages/index.adoc
docs/modules/plugin/nav.adoc
docs/modules/plugin/pages/compatibility-matrix.adoc
docs/modules/site-integration/nav.adoc
docs/modules/site-integration/pages/compatibility-matrix.adoc
docs/modules/site-integration/pages/introduction.adoc
docs/modules/site-integration/pages/setup-and-configuration.adoc

Adds list of supported versions for maven plugin and site integration
List supported versions and specially clarify what versions of maven-site-plugin & AsciidoctorJ are supported.
If we had a high cadence of changes and releases we could consider add integration test, but for current scenario I don't think it's necessary.
No
Fixes #567 

Add compatibility matrix

---

README.adoc

Add missing reference to 2.1.0 readme.
2.1.0 is the last version not present in docs.asciidoctor.org but still supported, so we need to make it more visible.
No
No
This is so minor is not worth mentioning.

Add missing 2.1.0 readme reference to README

---

CHANGELOG.adoc
README.adoc
docs/antora.yml

Updating docs in preparation for release as per my notes: https://github.com/abelsromero/asciidoctor-maven-plugin/wiki/Maven-release-steps

Update docs references for v2.2.2 release

---

CHANGELOG.adoc
docs/modules/site-integration/pages/compatibility-matrix.adoc
pom.xml
src/it/maven-site-plugin/pom.xml

Maintenance chore, bumping site related dependencies to most up to date compatible versions (docs included.)
Also tested maven-site-plugin v3.11.0 locally to make sure all versions between 3.10 and 3.12 are fine.
N/A
No big change, just maintenance
Not closing, but inspired by https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/578

Bump Doxia to v1.11.1 & maven-site-plugin IT to v3.12.0

---

CHANGELOG.adoc
pom.xml

Fix CVE-2021-21290
Fix security warning related to CVE-2021-21290.
This ONLY impacts `http` and `auto-refresh` mojos, pipelinas using the plugin for normal conversion are not impacted.
No
No

Bump netty-codec-http to latest v4.1.77.Final

---

pom.xml

* JUnit to v5.8.2
* Assertj to v3.23.1
* Mockito to v 3.12.4
* Lombok to 1.18.24
Maintenanc chore to keep test dependencies not too old.
n/a
no

Bump test dependencies (JUnit 5.8.2, Assertj 3.23.1, ...)

---

CHANGELOG.adoc
pom.xml

* Align jRuby to v9.3.4.0
Maintenance
n/a
Users can still use Asciidoctorj v2.5.4 with current released asciidoctor-maven-plugin.

Bump Asciidoctorj to latest v2.5.4

---

docs/modules/site-integration/pages/compatibility-matrix.adoc
pom.xml
src/it/maven-site-plugin/pom.xml
src/it/maven-site-plugin/src/site/site.xml
src/main/java/org/asciidoctor/maven/site/AsciidoctorDoxiaParser.java
src/main/java/org/asciidoctor/maven/site/AsciidoctorDoxiaParserModule.java

* Bump Doxia to 2.0.0-M1
* Leave note in docs for release
* Use SLF4J in site module (https://github.com/apache/maven-doxia/pull/5)
* Reorder constructor args in AsciidoctorDoxiaParserModule
Fixes #578 
Make the site module compatible with latest maven-site-plugin 4.0.0-M1.
No. Basic process is just bumping Doxia and updating required changes.
maven-site-plugin v3.1x.x is still compatible. So in case of need we can still do a 2.2.3 release without breaking builds.
*Finally, please add a corresponding entry …

Make plugin compatible with maven-site-plugin 4.0.0-M1

---

CHANGELOG.adoc
pom.xml

Chore to mainting AsciidoctorJ dependency.
Bump AsciidoctorJ to latest v2.5.5.
n/a
n/a

Bump AsciidoctorJ to v2.5.5

---

CHANGELOG.adoc
asciidoctor-maven-plugin/src/main/java/org/asciidoctor/maven/extensions/AsciidoctorJExtensionRegistry.java
asciidoctor-maven-plugin/src/main/java/org/asciidoctor/maven/extensions/ExtensionRegistry.java
asciidoctor-maven-plugin/src/test/java/org/asciidoctor/maven/extensions/AsciidoctorJExtensionRegistryTest.java

* Stops any possible usage of AsciidoctorJ v1.6.x (long not supported)
* Fixes issue where registering a non-Processor class was ignored without error
* Small improvements to JavaDocs
closes #568
Mostly simplify code, functionality has been kept (other than fixing an un-reported error case).
We are still instantiating the Class internally to check it and report any error with it instead of passing it to AsciidoctorJ as string.
We could do it, but then AsciidoctorJ would instantiate it again, decreasing performace.
**Are there any implications …

Replace reflection by direct JavaExtensionRegistry calls

---

CHANGELOG.adoc
pom.xml

chore: bumping AsciidoctorJ related versions

Bump AsciidoctorJ v2.5.6 + jRuby v9.3.8.0

---

CHANGELOG.adoc
pom.xml

* maven-enforcer-plugin to v3.1.0
* maven-compiler-plugin to v3.10.1
* maven-javadoc-plugin to v3.4.1
* maven-jar-plugin to v3.3.0
* maven-surefire-plugin to v2.22.2
Maintenance :toolbox: 
Bump build related plugins
No
No

Bump build related Maven plugins

---

CHANGELOG.adoc
asciidoctor-maven-plugin/pom.xml

Fix CVE-2022-41915
Fix security warning related to CVE-2022-41915.
This ONLY impacts http and auto-refresh mojos, pipelinas using the plugin for normal conversion are not impacted.
No, but there is an open [PR #608](https://github.com/asciidoctor/asciidoctor-maven-plugin/pull/608) from dependabot, that can be closed with this.
No

Bump netty-codec-http to latest v4.1.87.Final

---

CHANGELOG.adoc
asciidoctor-maven-plugin/pom.xml

Update netty-codec-http to the latest patch level version for a potential patch release of the plugin.
This ONLY impacts http and auto-refresh mojos, pipelinas using the plugin for normal conversion are not impacted.
No.
No.

Bump netty-codec-http to latest v4.1.89.Final

---

CHANGELOG.adoc
pom.xml

Bump maven plugins versions for the build.
* maven-enforcer-plugin v3.2.1
* maven-compiler-plugin v3.11.0
* maven-release-plugin  3.0.0-M7
* maven-javadoc-plugin  v3.5.0
* maven-surefire-plugin v3.0.0
* maven-invoker-plugin  v3.4.0
maven-invoker-plugin v3.5.0 is failing (unable to download jruby :shrug: ). This does not impact the actual release artifact, so leaving it for now.
no
We won't know if there's an issue with maven-release-plugin until we release. But it …

Bump build plugin dependencies

---

.mvn/wrapper/maven-wrapper.properties
CHANGELOG.adoc
asciidoctor-converter-doxia-module/pom.xml
asciidoctor-maven-commons/pom.xml
asciidoctor-maven-plugin/pom.xml
asciidoctor-parser-doxia-module/pom.xml
pom.xml

Bump dependencies:
* maven-core v3.9.1
* commons-io v2.11.0
* plexus-utils v3.5.1
Plugins
* maven-plugin-plugin v3.8.1
* maven-plugin-annotations v3.8.1
* plexus-component-metadata v2.1.1
* maven-enforcer-plugin v3.2.1
* maven-compiler-plugin v3.11.0
* maven-release-plugin v3.0.0-M7 (validated it works fine with 2.2.3 release)
* maven-javadoc-plugin v3.5.0
* maven-surefire-plugin v3.7.0
* maven-invoker-plugin v3.4.0 (there's a known issue preventing v3.5.0 use)

Set minimal maven version to 3.9.x & bump dependencies

---

.github/workflows/build.yaml
README.adoc
docs/modules/plugin/pages/compatibility-matrix.adoc

* Use 's4u/setup-maven-action' GH action to test Maven compatibility matrix
* Defined formal Maven compatible version (1-year-old + most recent minor)
Ensure we properly support a few maven versions. There have been some breaking changes in 3.9.1 that brought this to attention.
We could have a script step installing sdkman and setting mvn in the path.
But this is extra code we'd need to maintain.
Everything is don by `s4u/setup-maven-action` so we are in theory losing some control, but in reality, nothing we really needed. We'll see how it goes. …

Apply 's4u/setup-maven-action' GH action

---

.github/workflows/build.yaml
CHANGELOG.adoc
README.adoc
docs/modules/plugin/pages/compatibility-matrix.adoc

Porting https://github.com/asciidoctor/asciidoctor-maven-plugin/pull/631 to v2.2.x branch

(v2.2.x) Test on multiple maven versions

---

CHANGELOG.adoc
README.adoc

* Fix missing CHANGELOG entry for maven #632
* Add missing v2.2.x readme reference in README.
* Add missing changelog entry from latest PR.
n/a
n/a

Add missing v2.2.x reference in README

---

.github/workflows/build.yaml
CHANGELOG.adoc
pom.xml

Bump build related plugins
* maven-enforcer-plugin   3.3.0
* maven-release-plugin    3.0.0
* maven-source-plugin     3.3.0
* maven-surefire-plugin   3.1.0
* maven-invoker-plugin    3.5.1
Not now, but we may use dependabot in the future.
no

Bump Maven plugins for build

---

CHANGELOG.adoc
asciidoctor-converter-doxia-module/pom.xml
asciidoctor-maven-plugin/pom.xml
asciidoctor-parser-doxia-module/pom.xml

Fix the following deprecation messages that appear with Maven v3.x
This is required to build the project with Maven v4-alphas.
No.
No.

Remove use of deprecated 'parent.version' Maven property

---

.github/workflows/build.yaml
CHANGELOG.adoc
src/it/maven-site-plugin-v3.10/invoker.properties
src/it/maven-site-plugin-v3.10/pom.xml
src/it/maven-site-plugin-v3.10/src/site/asciidoc/_include.adoc
src/it/maven-site-plugin-v3.10/src/site/asciidoc/file-with-toc.adoc
src/it/maven-site-plugin-v3.10/src/site/asciidoc/templates/paragraph.html.slim
src/it/maven-site-plugin-v3.10/src/site/site.xml
src/it/maven-site-plugin-v3.10/validate.bsh

This  new test validates the minimal maven-site-plugin supported version.
We could somehow parametrize the version and run the IT's twice, but that seems a lot of work.
In the long run, I'd like to have an extension similar to what we do in the [maven examples](https://github.com/asciidoctor/asciidoctor-maven-examples/tree/main/tests/src/test/java/org/asciidoctor/maven/examples/tests) to run end-to-end tests more easily and quicker.
no

Add IT for maven-site-plugin v3.10.0

---

pom.xml

A set of maintenance bumps to build plugins and dependencies
Build plugins
* jacoco-maven-plugin 0.8.10
* maven-enforcer-plugin 3.3.0
* maven-invoker-plugin 3.5.1
* maven-release-plugin 3.0.0
* maven-source-plugin 3.3.0
* maven-surefire-plugin 3.1.0
Maven dependencies
* maven-plugin-plugin, maven-plugin-annotations 3.9.0
* maven-core, maven-plugin-api 3.8.5
* plexus-utils 3.8.1
Plugin dependencies
* netty-codec-http 4.1.93.Final
Test dependencies
* junit-bom 5.9.3
* assertj-core 3.24.2
no
no

Bump build plugins and dependencies

---

.github/workflows/build.yaml
CHANGELOG.adoc
docs/modules/plugin/pages/v3-migration-guide.adoc
pom.xml

:point_right:  Breaking change
Set Java 11 as minimal version.
* Update maven-compiler-plugin to use 'release'
* Remove Java8 from CI
* Add info to migration guide
no
Users in need of Java8 will need to use v2.5.x of both the Maven plugin and Asciidoctor.
#652

Set Java 11 as minimal version

---

CHANGELOG.adoc
asciidoctor-maven-plugin/src/it/thread-safe/asciidoctor-project-1/pom.xml
asciidoctor-maven-plugin/src/it/thread-safe/asciidoctor-project-2/pom.xml
asciidoctor-maven-plugin/src/it/thread-safe/asciidoctor-project-3/pom.xml
asciidoctor-maven-plugin/src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java
asciidoctor-maven-plugin/src/test/java/org/asciidoctor/maven/AsciidoctorIntegrationTest.java
asciidoctor-maven-plugin/src/test/java/org/asciidoctor/maven/AsciidoctorMojoExtensionsTest.java
asciidoctor-maven-plugin/src/test/java/org/asciidoctor/maven/AsciidoctorMojoLogHandlerTest.java
asciidoctor-maven-plugin/src/test/java/org/asciidoctor/maven/AsciidoctorMojoTest.java
asciidoctor-maven-plugin/src/test/java/org/asciidoctor/maven/AsciidoctorRefreshMojoTest.java
docs/modules/plugin/pages/usage.adoc
docs/modules/plugin/pages/v3-migration-guide.adoc
docs/modules/plugin/partials/process-asciidoc-mojo-parameters.adoc

:point_right: Breaking change for v3
Also:
* Update tests
* Update docs
* Add section to v3 migration guide
No. Using v3 to introduce breaking changes.
Users will need to change `headerFooter` by `standalone`.
Closes #649 

(v3.0.x) Replace deprecated 'headerFooter' by 'standalone' in configuration

---

CHANGELOG.adoc
asciidoctor-maven-plugin/src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java

Internal change, remove the use of unnecessary calls to AsciidoctorJ's `destinationDir`.
Remove the use of unnecessary calls to AsciidoctorJ's `destinationDir`.
no
no
Closes #650

(v3.0.x) Remove use of destinationDir

---

CHANGELOG.adoc
asciidoctor-converter-doxia-module/src/main/java/org/asciidoctor/maven/site/AsciidoctorConverterDoxiaParser.java
asciidoctor-maven-commons/src/main/java/org/asciidoctor/maven/site/SiteConversionConfiguration.java
asciidoctor-maven-commons/src/main/java/org/asciidoctor/maven/site/SiteConversionConfigurationParser.java
asciidoctor-maven-commons/src/test/java/org/asciidoctor/maven/site/SiteConversionConfigurationParserTest.java
asciidoctor-maven-plugin/src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java
asciidoctor-maven-plugin/src/main/java/org/asciidoctor/maven/model/Resource.java
asciidoctor-maven-plugin/src/test/java/org/asciidoctor/maven/TestUtils.java
asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/ast/AsciidoctorAstDoxiaParser.java
pom.xml

Started to remove the use of AsciidoctorJ methods but I also fixes a bug in the site integration found during the refactor.
In short, maven project properties were not added as Asciidoctor attributes when no site configuration was added.
No.
For context, I bumped into AsciidoctorJ v3.0.0-alpha.1, fixed issues in API (not extensions), and then went back to v2.5.10 to ensure all was working fine.
No
Only the fix will be documented, the other changes …

Remove asciidoctorj deprecated methods usage

---

CHANGELOG.adoc
pom.xml

Fix #553 thanks to the new version of JRruby 9.4.5.0.
n/a
n/a. FTR, same fix is being applied to asciidoctorj

(main) Bump JRuby to v9.4.5.0

---

docs/modules/plugin/partials/basic-maven-setup.adoc

`<dependencies>` is missing, not a valid declaration as presented.
See title, Maven snippet is invalid.
No.
The snippet can now be copied (apart from the ellipsis, but I didn't want to change that too.

Fix basic maven setup snippet.

---

.github/dependabot.yml
CHANGELOG.adoc

Automate maintenance of dependencies.
Dependabot is not perfect, but having used it for some time I find it helps. Even if the bump breaks something, at least we get a notification and we see that in CI and can decide what to do. The alternative is depending on time or strength to go through bumps and hope for the best.
There are others. I only have first-hand knowledge [Renovate](https://github.com/renovatebot/renovate), which I don't like for some companiy and data collection policies. In general, alternatives depend on extra configurations and authorizations, Dependabot being integrated in GitHub makes things easier.
Note: …

Add Dependabot for non pinned dependencies

---

pom.xml
src/test/java/org/asciidoctor/maven/TestUtils.java

https://github.com/asciidoctor/asciidoctor-maven-plugin/pull/671 with code fixes.
As a nice extra, we could remove some nasty reflection from the mocks.

(v2.2.x): Bump org.apache.maven.shared:maven-filtering from 3.2.0 to 3.3.1

---

.github/workflows/build.yaml
.mvn/wrapper/maven-wrapper.properties

Bump Maven to latest for both dev and CI.
n/a
n/a

(main) Bump Maven to v3.9.6

---

.github/workflows/build.yaml
CHANGELOG.adoc
pom.xml

* Bump lombok 1.18.24 to 1.18.30 to support Java 21
* Update supported maven versions.
* Add Java 21 support to branch v2.2.x.
n/a
n/a

(v2.2.x) Bump maven to 3.9.6 for v2.2.x

---

README.adoc

Removed AppVeyor and TravisCI.

(main) Remove unused CI badges from README

---

README.adoc

Removed AppVeyor and TravisCI.

(v2.2.x) Remove unused CI badges from README

---

CHANGELOG.adoc
pom.xml
src/it/spi-registered-log/log-handler/pom.xml

Use latest AsciidoctorJ v2.5.11.
Dependabot did not detect it :thinking: I suspect because it's set in a property?
no
n/a

(v2.2.x) Bump Asciidoctorj to v2.5.11

---

CHANGELOG.adoc
asciidoctor-maven-plugin/src/it/spi-registered-log/log-handler/pom.xml
pom.xml

Use latest AsciidoctorJ v2.5.11.
Dependabot did not detect it :thinking: I suspect because it's set in a property?
no
n/a

(main) Bump Asciidoctorj to v2.5.11

---

.github/dependabot.yml

Limit to non-breaking version until integration is revisited
We could ignore completely, but I'd rather at least keep things to stable versions.
n/a

(main) Limit Coverall dependencies to patch bumps

---

.github/workflows/build.yaml
CHANGELOG.adoc
asciidoctor-maven-plugin/src/main/java/org/asciidoctor/maven/process/CopyResourcesProcessor.java
asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/ast/processors/AbstractSinkNodeProcessor.java

Ensure we don't find Javadoc issues right when are testing a release :facepalm: To achieve it, we add a job to CI to run Javadoc generation and fail if something is wrong.
We DO accept warnings though, these are complaints about getter/setters and other that do not add value imho.
We could enable Javadoc in the normal build, but that would slow the normal development and testing. I'd rather have it a separate CI job.
Contributors would need to be aware that Javadocs are now a requirement, at least no errors. …

(main) Fix and test Javadoc generation

---

CHANGELOG.adoc
asciidoctor-maven-plugin/pom.xml
pom.xml

Fix build warnings observed in my machine. In short, we needed to set the version for `maven-deploy-plugin` and place `<prerequisites>` in the actual maven plugin sub-module, not the root.
```
[WARNING] Some problems were encountered while building the effective model for org.asciidoctor:asciidoctor-maven-plugin:maven-plugin:3.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-deploy-plugin is missing. @ org.apache.maven:maven-model-builder:3.8.8:super-pom, jar:file:/home/asalgadr/.sdkman/candidates/maven/3.8.8/lib/maven-model-builder-3.8.8.jar!/org/apache/mave …
```

Fix missing maven-deploy and prerequisites Maven warnings

---

.github/dependabot.yml

Newer versions are not Java8 compatible
Avoid Dependabot bumps that we know are not compatible :point_right: mockito removed Java 8 compat with v5.x.x.
no
n/a

(main) Pin mockito to 4.x.x in branch v2.2.x

---

.github/dependabot.yml

`commons-io` hasn't been part of the Maven runtime for a long, long time. So we can manage ourselves as a direct plugin dependency.
no
no

(main) Remove commons-io exclusion from Dependabot

---

.github/dependabot.yml
CHANGELOG.adoc
asciidoctor-maven-plugin/pom.xml

Maven Plugin Tools is a set of tools (plugin, dependencies) to generate metadata required for the Maven plugin. As such, we can run the latest and use Dependabot to automate the management without issues.
We still have CI tests to validate backward compatibility.
Keep using a pinned older version, however that means we cannot use Dependabot. So we depend on manual action to update from time to time.
Since we have CI to test multiple Maven versions I don't think it makes sense to keep this "use older version" policy.
There will be other similar PRs like this for other dependencies.
**Are there any implications of this pull …

(main) Use latest maven-plugin-tools

---

.github/dependabot.yml
CHANGELOG.adoc
asciidoctor-converter-doxia-module/pom.xml
asciidoctor-parser-doxia-module/pom.xml
pom.xml

Similar to PR #717, to ease project maintenance
we can automate Doxia dependencies and use CI
to validate backward compatibility.
no
n/a

(main) Use latest Maven Doxia

---

.github/dependabot.yml
CHANGELOG.adoc
asciidoctor-converter-doxia-module/pom.xml
asciidoctor-maven-commons/pom.xml
asciidoctor-maven-plugin/pom.xml
asciidoctor-parser-doxia-module/pom.xml
pom.xml

Similar to PRs #717 and #719, to ease project maintenance
we can automate Maven (core and transitives) dependencies
and use CI to validate backward compatibility.
* Remove maven exclusion from Dependabot.
* Deleted direct references to dependencies that are provided
by maven-core: ideally we'd like to refer them if we use them,
but ther lack of a BOM make it un-practical.
* Rename build properties for ease of use.
* Fix mising 'url' in 'asciidoctor-parser-doxia-module' module.
no
**Are there any implications of this pull request? Anything a …

(main) Use latest Maven version

---

asciidoctor-maven-commons/src/test/java/org/asciidoctor/maven/site/Xpp3DoomBuilder.java

The underlying Xpp3Doom implementation removes
'getParent' support in latest version, so we need
to do keep track of the parent for our tests
Fixes #638
Maybe, but the fix is simple enough to simply get it done.
no
This is for tests only, no need to report in CHANGELOG.

(main) Implement parent support for tests in Xpp3DoomBuilder

---

.github/dependabot.yml

See https://github.com/asciidoctor/asciidoctor-maven-plugin/pull/721#issuecomment-1873429272
plexus-utils Maven from runtime can be overridden https://issues.apache.org/jira/browse/MNG-6965. However, using 4.0.0 means, we need to add org.codehaus.plexus:plexus-xml:jar:4.0.3 because org.codehaus.plexus.util.xml.Xpp3Dom has been extracted in a sub-module. And that pulls alpha dependencies (org.apache.maven:maven-api-xml). While it may work, we should integrate alpha dependencies in a stable release.
no
no …

(main) Pin org.codehaus.plexus:plexus-utils to use v3.x.x to avoid pulling alpha dependencies

---

CHANGELOG.adoc
src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java
src/test/java/org/asciidoctor/maven/AsciidoctorMojoTest.java

Fix #728 
Also improve message. We cannot get the exact name without duplication asciidoctor core logic, but now when outputFile is not set simply wildcard will be displayed instead of the source extension to avoid confusion:
```
[warn] Duplicated destination found: overwriting file: /.../path/single-output.*
```
We could only check for `toDir` (as done in `main` branch) but that would break builds using older AsciidoctorJ versions.
no

(v2.2.x) Fix empty destination path calculation for validation

---

CHANGELOG.adoc
asciidoctor-maven-plugin/src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java

Improvement to user messages.
Add improvements from PR https://github.com/asciidoctor/asciidoctor-maven-plugin/pull/730.
See #728 
Yes, the solution is not perfect but it would require to replicate all asciidoctor internal logic to get the target file.
In truth I wonder if we should remove the message all together :thinking: 
no

(main) Improve warning message when destination file is going to be replaced

---

pom.xml

Avoid upstream bug.
v3.3.1 introduced a change that causes confusing output when using 'project.baseDir' for resources path.
See https://issues.apache.org/jira/browse/MSHARED-1175
The old message when copying resouces is fine.
```
Copying 118 resources
```
But the new, while less informative, omits the source after "from" in some cases.
```
Copying 118 resources from  to target/generated-docs
```
No. I don't think we are loosing anything with the revert.
*Finally, please add a corresponding entry to …

(v2.2.x) Return maven-filtering to v3.3.0 from v3.3.1

---

.github/workflows/build.yaml
pom.xml

Unify release configuration with PR #736 done for main branch.
no
no

(v2.2.x) Test artifacts signature in CI

---

.github/workflows/release.yaml
CHANGELOG.adoc
asciidoctor-converter-doxia-module/pom.xml
asciidoctor-maven-commons/pom.xml
asciidoctor-maven-plugin/pom.xml
asciidoctor-parser-doxia-module/pom.xml
pom.xml

Adds release pipeline to do relases from GitHub Action
Closes #141
Automate releases to make the release process much easier, less error prone and avoid local configurations.
Note it requires:
* Configure secrets in repo
* `s4u/setup-maven-action` does not work, so under-the-hood actions are used https://github.com/s4u/setup-maven-action/issues/68
* It's still required to manually login into https://oss.sonatype.org to close and release.
I'll create a new GPG key only for CI, but the user used to upload to `oss.sonatype` is a token linked to my account.
**Are there any alternative ways to …

(main) Automate release using GH Actions

---

asciidoctor-parser-doxia-module/src/it/maven-site-plugin/src/site/asciidoc/sample.adoc
asciidoctor-parser-doxia-module/src/it/maven-site-plugin/validate.groovy
asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/ast/NodesSinker.java
asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/ast/processors/ListItemNodeProcessor.java
asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/ast/processors/ParagraphNodeProcessor.java
asciidoctor-parser-doxia-module/src/test/java/org/asciidoctor/maven/site/ast/AsciidoctorAstDoxiaParserTest.java
asciidoctor-parser-doxia-module/src/test/java/org/asciidoctor/maven/site/ast/processors/ListItemNodeProcessorTest.java
asciidoctor-parser-doxia-module/src/test/resources/sample.asciidoc
docs/modules/site-integration/pages/parser-module-setup-and-configuration.adoc

List (ordered and unordered) dosn't convert formatting (bold, monospace, etc.) and links.
n/a
no

(main) Doxia parser: fix missing formattings and links in lists

---

asciidoctor-parser-doxia-module/src/it/maven-site-plugin/src/site/asciidoc/sample.adoc
asciidoctor-parser-doxia-module/src/it/maven-site-plugin/validate.groovy
asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/ast/NodesSinker.java
asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/ast/processors/DescriptionListNodeProcessor.java
asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/ast/processors/ListItemNodeProcessor.java
asciidoctor-parser-doxia-module/src/test/java/org/asciidoctor/maven/site/ast/processors/DescriptionListNodeProcessorTest.java
asciidoctor-parser-doxia-module/src/test/java/org/asciidoctor/maven/site/ast/processors/test/Html.java
docs/modules/site-integration/pages/parser-module-setup-and-configuration.adoc

Add support for description lists https://docs.asciidoctor.org/asciidoc/latest/lists/description/ for the new maven-parser-doxia-module.
It feels like it. The fact that ordered and unordered lists tags are treated in `ListItemNodeProcessor` but for description lists I had to do the treatment on its own `NodeProcessor` make me thing there's some flaw in the current approach. But so far it works and release v3 should not be delayed.
no.
**Is it related to an existing …

Support description list in parser doxia module #751

---

asciidoctor-maven-plugin/src/main/java/org/asciidoctor/maven/AsciidoctorZipMojo.java

As a simple reminder.
Related to #145

Mark Zip mojo as deprecated for removal in next major

---

CHANGELOG.adoc
README.adoc
docs/antora.yml

(main ) Update docs for v3.0.0 release

---

docs/modules/plugin/pages/v3-migration-guide.adoc
docs/modules/site-integration/pages/parser-module-setup-and-configuration.adoc
docs/modules/site-integration/pages/v3-migration-guide.adoc

Address duplicated titles for migration guides (https://github.com/asciidoctor/docs.asciidoctor.org/pull/78#issuecomment-1947199056)
* Make the title different for plugin and site modules
* Other fixes and style reviews
no
no

Fix duplicated titles in 3.x.x migration guides

---

.github/ISSUE_TEMPLATE.md
README.adoc

Help users with questions locate the chat site.
no
no

Add references to Asciidoctor Chat (Zulip) to README and issue template

---

README.adoc

Fix chat URL to use preferred `chat.asciidoctor.org`
no
no

(main) Use 'chat.asciidoctor.org' for Zulip urls in README

---

.github/workflows/build.yaml
CHANGELOG.adoc

Fix javadoc build flakes in CI
```
**Failed to execute goal on project asciidoctor-maven-plugin: Could not resolve dependencies for project org.asciidoctor:asciidoctor-maven-plugin:maven-plugin:3.0.1-SNAPSHOT: The following artifacts could not be resolved: org.asciidoctor:asciidoctor-maven-commons:jar:3.0.1-SNAPSHOT (absent): Could not find artifact org.asciidoctor:asciidoctor-maven-commons:jar:3.0.1-SNAPSHOT -> [Help 1]**
````
This is an experiment :crossed_fingers: 
**Are there any implications of this pull request? Anything a user must …

Force artifact install when building javadocs in CI (#742)

---

CHANGELOG.adoc
asciidoctor-maven-plugin/src/main/java/org/asciidoctor/maven/process/CopyResourcesProcessor.java
asciidoctor-maven-plugin/src/test/java/org/asciidoctor/maven/process/CopyResourcesProcessorTest.java

Fix resource copy in multi-module project
*None*
*None*

(main) Fix resource copy in multi-module project (#838)

---

CHANGELOG.adoc
asciidoctor-converter-doxia-module/src/main/java/org/asciidoctor/maven/site/AsciidoctorConverterDoxiaParser.java
asciidoctor-maven-commons/src/main/java/org/asciidoctor/maven/site/SiteConversionConfigurationParser.java
asciidoctor-maven-plugin/src/test/java/org/asciidoctor/maven/AsciidoctorMojoExtensionsTest.java
asciidoctor-maven-plugin/src/test/java/org/asciidoctor/maven/io/TestFilesHelper.java
asciidoctor-maven-plugin/src/test/java/org/asciidoctor/maven/test/processors/ChangeAttributeValuePreprocessor.java
asciidoctor-maven-plugin/src/test/java/org/asciidoctor/maven/test/processors/FailingPreprocessor.java
asciidoctor-maven-plugin/src/test/java/org/asciidoctor/maven/test/processors/ManpageInlineMacroProcessor.java
asciidoctor-maven-plugin/src/test/java/org/asciidoctor/maven/test/processors/UriIncludeProcessor.java
docs/modules/plugin/pages/compatibility-matrix.adoc
pom.xml

~Experimental branch to test changes for Asciidoctorj v3.0.x (not for merging yet).~
Bump Asciidoctorj to v3.0.x:
* Fix pathing issues related to https://github.com/asciidoctor/asciidoctorj/pull/1249. TLDR; `toDir` for `AsciidoctorMojo`  and `baseDir` for Site Converter need to be absolute.
* Tests
* Update extensions examples used for integration testing
* Fix pathing issues (same as above :point_up: )
* Fix use of deprecated Options and Attributes builders in 'asciidoctor-converter-doxia-module'
:information_source: I run additional manual tests on AsciidoctorJ 2.5.13 and all is working fine since AsciidoctorJ v3 is binary compatible with 2.5.x :tada: 
NOTE: in case someone saw the previous description listing breaking changes, those no longer apply since they were already addressed in …

(main) Bump Asciidoctorj to v3.0.x

---

CHANGELOG.adoc
asciidoctor-parser-doxia-module/src/it/maven-site-plugin/validate.groovy
asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/parser/processors/ImageNodeProcessor.java
asciidoctor-parser-doxia-module/src/test/java/org/asciidoctor/maven/site/parser/processors/ImageNodeProcessorTest.java

Fix image tag not being closed in `asciidoctor-parser-doxia-module`.
The solution delegates in the proper sink `figureGraphics`, we could have simply applied the change with `rawText`.
But I think is important to rely in raw as little as possible.
Fixes https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/783

(main) Fix IMG tag closing in parser-doxia-module

---

CHANGELOG.adoc
asciidoctor-converter-doxia-module/pom.xml
asciidoctor-converter-doxia-module/src/it/maven-site-plugin/pom.xml
asciidoctor-converter-doxia-module/src/it/maven-site-plugin/src/site/site.xml
asciidoctor-converter-doxia-module/src/main/java/org/asciidoctor/maven/site/AsciidoctorConverterDoxiaParser.java
asciidoctor-parser-doxia-module/pom.xml
asciidoctor-parser-doxia-module/src/it/maven-site-plugin/pom.xml
asciidoctor-parser-doxia-module/src/it/maven-site-plugin/src/site/site.xml
asciidoctor-parser-doxia-module/src/it/maven-site-plugin/validate.groovy
asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/parser/AsciidoctorAstDoxiaParser.java
asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/parser/AsciidoctorAstDoxiaParserModule.java
asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/parser/processors/ImageNodeProcessor.java
asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/parser/processors/SectionNodeProcessor.java
asciidoctor-parser-doxia-module/src/test/java/org/asciidoctor/maven/site/parser/AsciidoctorAstDoxiaParserTest.java
asciidoctor-parser-doxia-module/src/test/java/org/asciidoctor/maven/site/parser/NodeSinkerTest.java
asciidoctor-parser-doxia-module/src/test/java/org/asciidoctor/maven/site/parser/processors/OrderedListNodeProcessorTest.java
asciidoctor-parser-doxia-module/src/test/java/org/asciidoctor/maven/site/parser/processors/SectionNodeProcessorTest.java
asciidoctor-parser-doxia-module/src/test/java/org/asciidoctor/maven/site/parser/processors/TableNodeProcessorTest.java
asciidoctor-parser-doxia-module/src/test/java/org/asciidoctor/maven/site/parser/processors/test/Html.java
asciidoctor-parser-doxia-module/src/test/java/org/asciidoctor/maven/site/parser/processors/test/TestNodeProcessorFactory.java
docs/modules/site-integration/pages/compatibility-matrix.adoc
pom.xml

* Bump Doxia and Doxia-sitetools to the same versions as maven-site-plugin (v2.0.x-MX)
* Apply required code changes to code and test
* Update site.xml in ITs to new novel (https://maven.apache.org/xsd/site-2.0.0.xsd)
TODO:
Add compatibility with maven-site-plugin v3.20.0.
This requires code, tests and documentation changes due to breaking changes introduced by Doxia.
We can try to get the code compatible with previous versions of maven-site-plugin.
But that would required doubling not only the code, but also tests due to changes in generated HTML.
For the sake of simplicity, if someone needs to use older maven-site-plugin, …

Add compatibility with maven-site-plugin v3.20.0

---

CHANGELOG.adoc
asciidoctor-parser-doxia-module/src/it/maven-site-plugin/src/site/asciidoc/sample.adoc
asciidoctor-parser-doxia-module/src/it/maven-site-plugin/validate.groovy
asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/parser/processors/ListingNodeProcessor.java
asciidoctor-parser-doxia-module/src/test/java/org/asciidoctor/maven/site/parser/processors/ListingNodeProcessorTest.java
docs/modules/site-integration/pages/parser-module-setup-and-configuration.adoc

Adding non Doxia/fluido supported feature.
For now we embed some styles. When we add more "un-supported" features we'd need to create a fluid compatible extra CSS and look into how to inject it and how to define custom CSS classes without breaking Fluido Skin.
This adds an AsciiDoc feature that is not supported natively by Doxia or Fluido skin
Fixes #935

Add support for code blocks titles in asciidoctor-parser-doxia-module

---

CHANGELOG.adoc
asciidoctor-parser-doxia-module/src/it/maven-site-plugin/src/site/asciidoc/sample.adoc
asciidoctor-parser-doxia-module/src/it/maven-site-plugin/validate.groovy
asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/parser/NodeSinker.java
asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/parser/processors/DocumentNodeProcessor.java
asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/parser/processors/ExampleNodeProcessor.java
asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/parser/processors/ImageNodeProcessor.java
asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/parser/processors/ListingNodeProcessor.java
asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/parser/processors/SectionNodeProcessor.java
asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/parser/processors/SinkAttributes.java
asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/parser/processors/Styles.java
asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/parser/processors/TableNodeProcessor.java
asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/parser/processors/TitleCaptionExtractor.java
asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/parser/processors/TitleExtractor.java
asciidoctor-parser-doxia-module/src/test/java/org/asciidoctor/maven/site/parser/AsciidoctorAstDoxiaParserTest.java
asciidoctor-parser-doxia-module/src/test/java/org/asciidoctor/maven/site/parser/NodeSinkerTest.java
asciidoctor-parser-doxia-module/src/test/java/org/asciidoctor/maven/site/parser/processors/DescriptionListNodeProcessorTest.java
asciidoctor-parser-doxia-module/src/test/java/org/asciidoctor/maven/site/parser/processors/ExampleNodeProcessorTest.java
asciidoctor-parser-doxia-module/src/test/java/org/asciidoctor/maven/site/parser/processors/ImageNodeProcessorTest.java
asciidoctor-parser-doxia-module/src/test/java/org/asciidoctor/maven/site/parser/processors/ListingNodeProcessorTest.java
asciidoctor-parser-doxia-module/src/test/java/org/asciidoctor/maven/site/parser/processors/OrderedListNodeProcessorTest.java
asciidoctor-parser-doxia-module/src/test/java/org/asciidoctor/maven/site/parser/processors/SectionNodeProcessorTest.java
asciidoctor-parser-doxia-module/src/test/java/org/asciidoctor/maven/site/parser/processors/TableNodeProcessorTest.java
asciidoctor-parser-doxia-module/src/test/java/org/asciidoctor/maven/site/parser/processors/UnorderedListNodeProcessorTest.java
asciidoctor-parser-doxia-module/src/test/java/org/asciidoctor/maven/site/parser/processors/test/Html.java
asciidoctor-parser-doxia-module/src/test/java/org/asciidoctor/maven/site/parser/processors/test/StringTestUtils.java
docs/modules/site-integration/pages/parser-module-setup-and-configuration.adoc

Still WIP:
* Added support for Example blocks
* Added support for captioned titles in tables, listing, figure, and examples.
- Missing: appendix
Working on examples made me realize the way we traverse the AST won't work.
We did some workaround for lists, making it so sub-blocks are traversed from a dedicated NodeProcessor.
But we can't apply the same for example, because it can contain many other elements. 
:thinking: 
~I will probably merge basic support for example nodes with a paragraph first and then work on the refactoring in another PR. This is experimental after all.~ :point_right: Done and rebased https://github.com/asciidoctor/asciidoctor-maven-plugin/pull/944
**Are …

Support "Captioned titles" in asciidoctor-parser-doxia-module

---

asciidoctor-converter-doxia-module/src/it/maven-site-plugin/pom.xml
asciidoctor-parser-doxia-module/src/it/maven-site-plugin/pom.xml
pom.xml

Bump maven-site-plugin to v3.21.0 + Doxia to v2.0.0.
Doxia is bumped to align with the version used in maven-site-plugin.
No
No

Bump maven-site-plugin to v3.21.0 + Doxia to v2.0.0

---

CHANGELOG.adoc
asciidoctor-converter-doxia-module/src/main/java/org/asciidoctor/maven/site/AsciidoctorConverterDoxiaParser.java
asciidoctor-maven-commons/src/main/java/org/asciidoctor/maven/log/MemoryLogHandler.java
asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/parser/AsciidoctorAstDoxiaParser.java
docs/modules/site-integration/pages/converter-module-setup-and-configuration.adoc
docs/modules/site-integration/pages/parser-module-setup-and-configuration.adoc

This PR uses the new 'reference' parameter in Doxia Parsers to print the source filename when an issue is detected. This is compatible and extends the features in 'logHandler'.
Fixes #323
No
No. In fact, the behavior is slightly different from `process-asciidoc` mojo to minimize changes.
See comment https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/323#issuecomment-2442617895

Add INFO message to site modules showing the filename in case of issues

---

.github/dependabot.yml
pom.xml

Just realized we were ignoring jRuby bumps.
I am removing it, we need to prioritize ease if maintenance before aligning to AsciidoctorJ.
If thanks to the Dependabot bumps we found some incompatibility, the better, we can research and contribute to AsciidoctorJ
no
no

Bump JRuby to latest 9.4.8.0

---

CHANGELOG.adoc
asciidoctor-converter-doxia-module/src/main/java/org/asciidoctor/maven/site/AsciidoctorConverterDoxiaParser.java
asciidoctor-converter-doxia-module/src/test/java/org/asciidoctor/maven/site/AsciidoctorConverterDoxiaParserTest.java
asciidoctor-converter-doxia-module/src/test/resources/with-locale/en/asciidoc/included.adoc
asciidoctor-converter-doxia-module/src/test/resources/with-locale/en/asciidoc/sample.adoc
asciidoctor-maven-commons/src/main/java/org/asciidoctor/maven/site/SiteBaseDirResolver.java
asciidoctor-maven-commons/src/test/java/org/asciidoctor/maven/site/SiteBaseDirResolverTest.java
asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/parser/AsciidoctorAstDoxiaParser.java
asciidoctor-parser-doxia-module/src/test/java/org/asciidoctor/maven/site/parser/AsciidoctorAstDoxiaParserTest.java
asciidoctor-parser-doxia-module/src/test/resources/with-locale/en/asciidoc/included.adoc
asciidoctor-parser-doxia-module/src/test/resources/with-locale/en/asciidoc/sample.adoc

The calculation now takes into consideration locale and siteDirectory correctly. All of this when user does not explicitly sets `baseDir`  in the 
For better compatibility with older maven-site plugin we could have tried some reflection to "guess" the version, but this adds "IMO" unnecessary complexity. Users should be incentivized to upgrade. 
1. This is done for conventions in maven-site v3.20.+
Users with older versions should upgrade or avoid using locales. As a workaround, multiple executions with siteDirectory can be configured.
2. Currently …

(main) Fix resolution of baseDir in site-integration

---

asciidoctor-maven-commons/pom.xml
asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/parser/processors/ExampleNodeProcessor.java
asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/parser/processors/ImageNodeProcessor.java
asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/parser/processors/SinkAttributes.java
asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/parser/processors/Styles.java
asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/parser/processors/TableNodeProcessor.java
asciidoctor-parser-doxia-module/src/test/java/org/asciidoctor/maven/site/parser/processors/ExampleNodeProcessorTest.java
asciidoctor-parser-doxia-module/src/test/java/org/asciidoctor/maven/site/parser/processors/TableNodeProcessorTest.java
asciidoctor-parser-doxia-module/src/test/java/org/asciidoctor/maven/site/parser/processors/test/Html.java

This prevents other colors from leaking into white rows. For example when the table is in an example block.
Probably, I am by no means a CSS expert.
No
Fixes #948

(main) Force white background in parser-doxia-module tables

---

.github/workflows/build-maven-4.yaml
CHANGELOG.adoc
asciidoctor-converter-doxia-module/src/main/java/org/asciidoctor/maven/site/AsciidoctorConverterDoxiaParser.java
asciidoctor-converter-doxia-module/src/main/java/org/asciidoctor/maven/site/AsciidoctorConverterDoxiaParserModule.java
asciidoctor-converter-doxia-module/src/main/java/org/asciidoctor/maven/site/SiteConverterDecorator.java
asciidoctor-converter-doxia-module/src/test/java/org/asciidoctor/maven/site/AsciidoctorConverterDoxiaParserTest.java
asciidoctor-converter-doxia-module/src/test/java/org/asciidoctor/maven/site/SiteConverterDecoratorTest.java
asciidoctor-maven-commons/pom.xml
asciidoctor-maven-commons/src/main/java/org/asciidoctor/maven/site/LogHandlerFactory.java
asciidoctor-maven-commons/src/main/java/org/asciidoctor/maven/site/SiteBaseDirResolver.java
asciidoctor-maven-commons/src/main/java/org/asciidoctor/maven/site/SiteConversionConfiguration.java
asciidoctor-maven-commons/src/main/java/org/asciidoctor/maven/site/SiteConversionConfigurationParser.java
asciidoctor-maven-commons/src/test/java/org/asciidoctor/maven/site/SiteConversionConfigurationParserTest.java
asciidoctor-maven-plugin/src/main/java/org/asciidoctor/maven/AsciidoctorHttpMojo.java
asciidoctor-maven-plugin/src/main/java/org/asciidoctor/maven/AsciidoctorJFactory.java
asciidoctor-maven-plugin/src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java
asciidoctor-maven-plugin/src/main/java/org/asciidoctor/maven/AsciidoctorOptionsFactory.java
asciidoctor-maven-plugin/src/main/java/org/asciidoctor/maven/AsciidoctorRefreshMojo.java
asciidoctor-maven-plugin/src/main/java/org/asciidoctor/maven/AsciidoctorZipMojo.java
asciidoctor-maven-plugin/src/main/java/org/asciidoctor/maven/http/AsciidoctorHandler.java
asciidoctor-maven-plugin/src/main/java/org/asciidoctor/maven/process/CopyResourcesProcessor.java
asciidoctor-maven-plugin/src/main/java/org/asciidoctor/maven/process/ResourcesProcessor.java
asciidoctor-maven-plugin/src/main/java/org/asciidoctor/maven/process/SourceDirectoryFinder.java
asciidoctor-maven-plugin/src/main/java/org/asciidoctor/maven/process/SourceDocumentFinder.java
asciidoctor-maven-plugin/src/test/java/org/asciidoctor/maven/process/CopyResourcesProcessorTest.java
asciidoctor-maven-plugin/src/test/java/org/asciidoctor/maven/refresh/ResourceCopyFileAlterationListenerAdaptorTest.java
asciidoctor-maven-plugin/src/test/java/org/asciidoctor/maven/test/MojoMocker.java
asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/parser/AsciidoctorAstDoxiaParser.java
asciidoctor-parser-doxia-module/src/test/java/org/asciidoctor/maven/site/parser/AsciidoctorAstDoxiaParserTest.java
pom.xml

Use Eclipse Sisu for dependency injection to better organize code. We have been using manual instance creation and that's limiting how modular we can make the code (TLDR; it's easier to create static method helper classes or private methods than cohesive components).
This has already allowed some simple refactors (more to come), and reduce usage of reflection for testing.
Notes:
* For now we pass `Log` to methods for simplicity. With Maven 4 that will be removed in favor of normal slf4j.
Still experimenting.
**Are there any implications of this …

(main) Use Maven Eclipse Sisu to inject components

---

CHANGELOG.adoc
asciidoctor-maven-commons/src/main/java/org/asciidoctor/maven/log/CapturedLogRecord.java
asciidoctor-maven-commons/src/main/java/org/asciidoctor/maven/log/LogHandler.java
asciidoctor-maven-commons/src/main/java/org/asciidoctor/maven/log/LogRecordsProcessors.java
asciidoctor-maven-commons/src/main/java/org/asciidoctor/maven/log/MemoryLogHandler.java
asciidoctor-maven-commons/src/main/java/org/asciidoctor/maven/site/SiteLogHandlerDeserializer.java
asciidoctor-maven-commons/src/test/java/org/asciidoctor/maven/log/CapturedLogRecordTest.java
asciidoctor-maven-commons/src/test/java/org/asciidoctor/maven/log/LogRecordFormatterTest.java
asciidoctor-maven-commons/src/test/java/org/asciidoctor/maven/log/LogRecordsProcessorsTest.java
asciidoctor-maven-commons/src/test/java/org/asciidoctor/maven/log/MemoryLogHandlerTest.java
asciidoctor-maven-commons/src/test/java/org/asciidoctor/maven/log/TestCursor.java
asciidoctor-maven-commons/src/test/java/org/asciidoctor/maven/log/TestLogRecords.java
asciidoctor-maven-commons/src/test/java/org/asciidoctor/maven/site/SiteLogHandlerDeserializerTest.java
asciidoctor-maven-plugin/src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java
asciidoctor-maven-plugin/src/main/java/org/asciidoctor/maven/process/SourceDocumentFinder.java
asciidoctor-maven-plugin/src/test/java/org/asciidoctor/maven/AsciidoctorMojoLogHandlerTest.java
asciidoctor-maven-plugin/src/test/resources/src/asciidoctor/errors/valid.adoc
docs/modules/plugin/partials/process-asciidoc-mojo-parameters.adoc

Allows to see all errors in all files before reporting a build failure. Previously, build failed on the first error found.
See https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/1023
The approach opts to extend the current features for minimal changes.
See the whole conversation in the linked issue for context.
No.
The default behavior remains the same.

Add failFast option to allow displaying all errors in build

---

CHANGELOG.adoc
pom.xml

Fixes maven-compiler-plugin configuration to ensure compatibility with Java 11.
Luckily, CI configuration ensures compatibility with Java 11 is guaranteed.
n/a
n/a

Set maven-compiler-plugin release to Java 11
