src/main/java/org/asciidoctor/maven/extensions/ExtensionRegistry.java, src/main/java/org/asciidoctor/maven/site/AsciidoctorParser.java
Minor fixes in the javadocs to ensure the whole release process works without problems
=> javadoc fixes

src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java, src/test/groovy/org/asciidoctor/maven/test/AsciidoctorMojoTest.groovy, src/test/resources/src/asciidoctor/book.adoc
- add test to ensure doctype set in document header is honored
- add assertion to verify default doctype is article
- minor code cleanups
=> resolves #119 honor doctype set in document header

pom.xml
Aligning the version of JRuby with the one used in AsciidoctorJ to prevent issues detected on Windows.
=> fixes issue #189 -Downgrade jRuby version to 1.7.21

src/test/groovy/org/asciidoctor/maven/test/AsciidoctorMojoTest.groovy, src/test/resources/src/asciidoctor/github-include.adoc
As mentioned in isse #153 this test will ensure that we keep track of the issue when we finally fix it.
It has been tested that with jruby 9k the issue is resolved. When that happens (e.g., moving to Asciidoctorj 1.6.0) this tails will fail and will need to be updated.
=> Reminder for issue #153

src/main/java/org/asciidoctor/maven/AsciidoctorZipMojo.java
https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/215
=> FIX ISSUE #215

pom.xml, src/main/java/org/asciidoctor/maven/http/AsciidoctorHandler.java, src/main/java/org/asciidoctor/maven/http/AsciidoctorHttpServer.java
Upgrading Netty and some maven plugins.
I'd like to get this working on Java 9; there is still much more to do but this is a start.
=> Upgrading Netty

pom.xml
o Removed superflous scope compile cause it is default scope.
=> Fixed #231

pom.xml
o upgraded maven-source-plugin to version 3.0.1
=> Fixed #235

src/it/article-html-command/invoker.properties, src/it/article-html-command/src/main/doc/sample.asciidoc, src/it/article-html-command/validate.groovy
Test validates that attributes passed as `-Dasciidoctor.attributes` are correctly processed.
=> Added additional validations to integration test 'article-html-command'

pom.xml
o maven-plugin-annotation dependency should be scope provided
=> Fixed #240

pom.xml
o keep maven-plugin-plugin and maven-plugin-annotations sync
using the same version.
=> Fixed #238

src/main/java/org/asciidoctor/maven/io/AsciidoctorFileScanner.java, src/test/groovy/org/asciidoctor/maven/test/AsciidoctorMojoTest.groovy, src/test/resources/src/asciidoctor/sample-with-doc-info-docinfo-footer.html, src/test/resources/src/asciidoctor/sample-with-doc-info-docinfo-footer.xml, src/test/resources/src/asciidoctor/sample-with-doc-info-docinfo.html, src/test/resources/src/asciidoctor/sample-with-doc-info-docinfo.xml, src/test/resources/src/asciidoctor/sample-with-doc-info.asciidoc
Fixes https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/269
=> 269 Exclude docinfo files by default

README.adoc
In the meantime a final implementation is provided, a note has been added to README to clarify that some backends need additional configurations when multiple resources are set.
=> related to #291 - added note regarding configuration of multiple resources

pom.xml
=> Upgrade asciidoctorj to 1.5.6

pom.xml
All plugin versions but those related to maven itself have been updated to latest version (to be revieweed in another PR to close related current issues).
As a nice touch invoker-plugin has a much nicer output for integration tests.
=> Updated plugins versions

README.adoc
Added:
* Clarification on AsciiDoc documents and resources locations
* Detailed list of supported options in the site: with its limitations and quirks
=> Improved site mojo documentation in README

src/main/java/org/asciidoctor/maven/http/AsciidoctorHttpServer.java
Today the server only works on localhost
=> Be able to use LAN IP

pom.xml, src/test/groovy/org/asciidoctor/maven/test/AsciidoctorMojoLogHandlerTest.groovy, src/test/groovy/org/asciidoctor/maven/test/AsciidoctorMojoTest.groovy, src/test/resources/src/asciidoctor/main-document.adoc
Minor refactors to avoid nasty errors when some tests fail + minor refactors
=> added extra assertions to failing tests to avoid NullPointers

README.adoc, src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java, src/test/groovy/org/asciidoctor/maven/test/AsciidoctorMojoTest.groovy, src/test/resources/templates/set-1/admonition.html.slim, src/test/resources/templates/set-2/block_paragraph.html.slim
Related to https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/265.
This PR add the new option `templateDirs` without removing `templateDir`.
=> Added templateDirs configuration option

src/main/java/org/asciidoctor/maven/extensions/AsciidoctorJExtensionRegistry.java
=> correct wrong reference in AsciidoctorJExtensionRegistry javadoc

pom.xml
All unit and it testes have been validated.
=> Update AsciidoctorJ to v2.0.0

README.adoc
=> Make sample resource config valid xml

pom.xml
This PR upgrades AsciidoctorJ version to latest 2.3.0.
=> Bumps Asciidoctorj version to latest 2.3.0

README.adoc, src/it/uses-html5-as-default-backend/invoker.properties, src/it/uses-html5-as-default-backend/pom.xml, src/it/uses-html5-as-default-backend/src/main/asciidoc/sample.asciidoc, src/it/uses-html5-as-default-backend/validate.groovy, src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java
This PR:
* Sets html5 as default backend
* Updated README accordingly
* Adds integration test accordigly
=> closes #188: sets html5 as default backend

README.adoc, README_zh-CN.adoc, src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java, src/test/groovy/org/asciidoctor/maven/test/AsciidoctorMojoTest.groovy, src/test/groovy/org/asciidoctor/maven/test/AsciidoctorZipMojoTest.groovy
This PR:
* Removes the sourceHighlighter configuration property
* Updates tests accordingly
* Updates README accordingly
=> removes sourceHighlighter mojo configuration in favour of attributes

docs/v2-migration-guide.adoc
Adds a reviewed version of the guide previously shared in the discussion issue.
=> Adds v2.x.x migration guide

CHANGELOG.adoc, README.adoc
This PR:
* Adds v2.x.x migration guide reference in README for findability
* Adds CHANGELOG for better handling of changes in the future (inspired by Asciidoctorj's)
=> adds v2.x.x migration guide reference in README for findability

CHANGELOG.adoc, pom.xml
Update `jacoco-maven-plugin` to latest version.
n/a
n/a
=> bumps jacoco-maven-plugin to 0.8.5

CHANGELOG.adoc, pom.xml, src/test/java/org/asciidoctor/maven/io/ConsoleHolder.java
Upgrades AsciidoctorJ version to latests 2.4.1 and JRuby to 9.2.13.0
No
No
=> bumps Asciidoctorj to 2.4.1 + jRuby to 9.2.13.0

README.adoc
:point_right: Release preparation :rocket: 
Update the release info in the README. Doing this now, the rest of the process is automatic.
No, that I have been able to find.
Release needs to be run immediately!
=> updates README for next release 2.1.0

CHANGELOG.adoc
Just prepapre the CHANGELOG for future changes.
N/A
No
=> Promote unreleased changes to v2.1.0 in CHANGELOG

.github/workflows/build-publish-docs.yaml
Fix docs branch in GH-Action `build-publish-docs`.
No.
N/A
=> Fix docs GH-Action branch

docs/modules/ROOT/pages/index.adoc
Align the root/index title to requirement for the new docs.asciidoctor site :partying_face: 
N/A
N/A
=> Align title with docs.asciidoctor.org site requirements

docs/antora.yml
Align Antora component name with final title agreed.
Not that I am aware.
N/A
=> Align Antora component name with title

docs/modules/plugin/partials/process-asciidoc-mojo-parameters.adoc
**What kind of change does this PR introduce?**
Fix a broken deep link.
=> add missing anchor for setting boolean attribute values

README.adoc
Previous commit https://github.com/asciidoctor/asciidoctor-maven-plugin/commit/698ad02897e676023e2770cfffd3b3105e178ef2 introduced this issue because it changes the published url.
No
N/A
=> Update uri-docs in README

CHANGELOG.adoc, pom.xml, src/main/java/org/asciidoctor/maven/http/AsciidoctorHandler.java, src/main/java/org/asciidoctor/maven/http/AsciidoctorHttpServer.java
Upgrade netty-codec-http used for `http` and `auto-refresh` goals as noted in https://github.com/asciidoctor/asciidoctor-maven-plugin/pull/508.
No
No, tests (should) ensure no feature is broken.
=> Upgrade netty codec http

README.adoc
Add Zulip badge to README for discoverability.
No.
No
=> Add Zulip badge to README

CHANGELOG.adoc, pom.xml
Bump Asciidoctorj to latest version.
n/a
Also bumps jRuby.
=> Bump Asciidoctorj to 2.5.0

CHANGELOG.adoc, pom.xml, src/it/spi-registered-log/log-handler/pom.xml
Chore to align with latest Asciidoctorj version
No
No
=> Bump Asciidoctorj to v2.5.1

CHANGELOG.adoc
Update CHANGELOG to refrect fix on issue #415
=> Update CHANGELOG to refrect fix on issue #415

CHANGELOG.adoc, README.adoc, pom.xml
* Apply changes to deploy in MavenCentral without using Bintray.
* Update references fro 2.2.0 release.
n/a
n/a
=> Prepare v2.2.0 release in MavenCentral

CHANGELOG.adoc
=> Add missing changelog entry for PR #555

CHANGELOG.adoc, pom.xml
Bump Asciidoctorj to latest v2.5.2.
No.
No
=> Bump Asciidoctorj to v2.5.2

.github/workflows/build.yaml, .mvn/wrapper/maven-wrapper.properties, CHANGELOG.adoc, pom.xml
Add support for Java 17.
No
Also updates actions to newer versions.
=> Add Java17 to ci pipelines

CHANGELOG.adoc, pom.xml
Chore: keeping up with AsciidoctorJ released versions :rocket: 
No
No
=> Bump Asciidoctorj to v2.5.3 & JRuby to v 9.2.20.1

CHANGELOG.adoc
=> Fix invalid PR reference in CHANGELOG

CHANGELOG.adoc, pom.xml, src/it/maven-site-plugin/pom.xml, src/it/maven-site-plugin/src/site/site.xml
* Bump maven-site-plugin in IT to v4.0.0-M3
Bump doxia to latest version.
n/a
Both Doxia version and maven-stite are still milestones.
- [] No
Making sure we are on latests  versions for #589
=> Bump doxia-core to v2.0.0-M3

README.adoc, docs/modules/plugin/pages/usage.adoc
=> Fix absolute to relative path

CHANGELOG.adoc, docs/modules/plugin/pages/goals/http.adoc, docs/modules/plugin/pages/goals/process-asciidoc.adoc
Update changelog before I totally forget about it :roll_eyes: 
n/a
OS contributions are great!
Not issue, but PR https://github.com/asciidoctor/asciidoctor-maven-plugin/pull/592
=> Update CHANGELOG: add contribution #592 docs fixes

docs/modules/ROOT/pages/index.adoc, docs/modules/plugin/pages/compatibility-matrix.adoc, docs/modules/plugin/pages/goals/auto-refresh.adoc, docs/modules/plugin/pages/goals/http.adoc, docs/modules/plugin/pages/introduction.adoc, docs/modules/plugin/pages/tips-and-tricks.adoc, docs/modules/plugin/pages/v2-migration-guide.adoc, docs/modules/plugin/partials/basic-maven-setup.adoc, docs/modules/project/pages/contributing.adoc
=> Proofread documentation

CHANGELOG.adoc, docs/antora.yml, docs/modules/plugin/pages/compatibility-matrix.adoc, docs/modules/plugin/pages/v2-migration-guide.adoc, docs/modules/plugin/pages/v3-migration-guide.adoc
Add v2 to v3 migration guide to help users whith the upgrade.
n/a
n/a
=> Add v3.x.x migration guide

asciidoctor-maven-plugin/src/main/java/org/asciidoctor/maven/io/Zips.java
Simple refactor to avoid code warnings.
Remove use od some deprecated APIs.
No.
No. Code affects internals unsupported mojo.
Not relevant enough to mention.
=> Use try-resource to remove deprecated APIs in Zips

asciidoctor-maven-plugin/src/main/java/org/asciidoctor/maven/AsciidoctorMojo.java, asciidoctor-maven-plugin/src/main/java/org/asciidoctor/maven/refresh/ResourceCopyFileAlterationListenerAdaptor.java
Leftover from #597
Remove an unnecessary method introduced in PR #597 
no
no
Not worth mentioning.
=> Remove unnecessary mapResources method

CHANGELOG.adoc, asciidoctor-maven-plugin/src/test/java/org/asciidoctor/maven/AsciidoctorIntegrationTest.java, pom.xml
Test latest Asciidoctorj v2.5.7
=> Bump AsciidoctorJ to v2.5.7

.github/workflows/build.yaml
CI :robot:  all the branches!
Ensure tests run for 2.2.x PRs too.
no
no
=> Enable GH actions pipelines for 2.2.x branch

.github/workflows/build.yaml, CHANGELOG.adoc
Removing some warnings that have been appearing in GH actions builds about deprecated configurations.
no
no
=> Bump gh actions checkout and setup-java

CHANGELOG.adoc, README.adoc, docs/antora.yml, docs/modules/site-integration/pages/compatibility-matrix.adoc, pom.xml, src/it/maven-site-plugin/pom.xml
Bump maven-site related components to latest stable versions.
no
no
=> Bump Doxia to v1.12.0 and maven-site-plugin in IT to 3.12.1

CHANGELOG.adoc, README.adoc, docs/antora.yml
Preparing v2.2.3 release :crossed_fingers:
=> Update properties in docs for v2.2.3 release

CHANGELOG.adoc, asciidoctor-maven-plugin/pom.xml
Bump netty to latest for CVE reports.
Also porting this from v2.2.x branch.
no
bo
=> Bump netty-codec-http to v4.1.90.Final

CHANGELOG.adoc, pom.xml
* Bump AsciidoctorJ to v2.5.8
* Bump JRuby to v9.3.10.0
Chore to bump AsciidoctorJ & JRuby
no
no
=> Bump AsciidoctorJ to latest

CHANGELOG.adoc, pom.xml, src/it/spi-registered-log/log-handler/pom.xml
Tha
Fix false Maven warning starting from v3.9.2 #634 
We could wait until fixes appear in Maven upstream, which leaves users with warning messages in the meantime.
#634 
=> Apply Maven workarrounds

CHANGELOG.adoc, README.adoc, docs/antora.yml
Update docs in preparation for v2.2.4 release.
Cleanup done in the list of old versions to remove the very old unsupported.
=> (v2.2.x) Update docs for v2.2.4 release

CHANGELOG.adoc, pom.xml
Else, an error reporting the plugin is run twice is shown.
Fixes #644
Prevent an error during the release.
It was detected and fixed for v2.2.x during v2.2.4 release.
no
no
- [] No
#644
=> Fix maven-source-plugin configuration for release

CHANGELOG.adoc, pom.xml
Bump Asciidoctorj to v2.5.10 & jRuby to v9.4.2.0
no
no
=> (v3.0.x) Bump Asciidoctorj to v2.5.10 & jRuby to v9.4.2.0

CHANGELOG.adoc, pom.xml
Bump Asciidoctorj to v2.5.10 & jRuby to v9.4.2.0
no
no
=> (v2.2.x) Bump Asciidoctorj to v2.5.10 & jRuby to v9.4.2.0

.github/workflows/build.yaml, .mvn/wrapper/maven-wrapper.properties, CHANGELOG.adoc
Keep up with latest Maven version (v3.9.5).
n/a
n/a
=> (main) Bump Maven wrapper to 3.9.5

.github/workflows/build.yaml, CHANGELOG.adoc, pom.xml
* Required bump of Lombok to 1.18.30
Test builds on latest Java LTS, v21.
n/a.
=> (main) Add Java 21 to CI

CHANGELOG.adoc, pom.xml
Fixes #553
Fix https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/553 thanks to the new version of JRruby 9.4.5.0.
n/a
n/a. FTR, same fix is being applied to asciidoctorj
=> (v2.2.x) Bump JRuby to v9.4.5.0 (fixes #553)

docs/modules/plugin/partials/basic-maven-setup.adoc
Cherry-pick of https://github.com/asciidoctor/asciidoctor-maven-plugin/pull/667 to maintenance branch
=> (v2.2.x) Fix basic maven setup snippet (#667)

.github/dependabot.yml, CHANGELOG.adoc, asciidoctor-converter-doxia-module/pom.xml, asciidoctor-maven-plugin/pom.xml, asciidoctor-parser-doxia-module/pom.xml, pom.xml
I've seen some dependency bumps missing from Dependabot. I don't see an exact reason, for instance, some plugins in `pluginManagement` received a bump PR, but others don't. Same for some dependencies.
The main goal of this PR is to increase Dependabot to daily schedule to see if those missing dependencies are detected at some point.
It also includes other changes are relted to dependency management.
* Set Dependabot interval to 'daily'
* Set jacoco version directly for better Dependabot recognition
* Removed unnecessary property 'project.execution.environment'
* Move coveralls plugin to parent 'pluginManagement' for better Dependabot recognition
**Are there any alternative ways …
=> (main) Improve dependency management

pom.xml
Bump mockito to latest Java 8 compatible version. We'd also not to pin the version to avoid automatic bumps.
no
n/a
=> (v.2.2.x) Bump mockito to v4.11.0

.github/workflows/build.yaml, CHANGELOG.adoc, pom.xml
- Remove release risks by running parts of it alongside other tests :safety_vest: 
- Experiment to eventually automate the whole release process :rocket: 
Test the signature of artifacts in CI.
Yes, regarding where and how to store the keys.
In the end, I decided to put them in the same code for reasons (it's a test key after all):
1. Simpler, all resides in one place.
2. Secrets don't work in PRs and I even had issues when setting environment variables in my fork (always empty :shrug:).
no
*Finally, please …
=> Test artifacts signature in CI

.github/dependabot.yml
Reduce distraction. Having all PRs on Monday makes it less time consuming.
No.
No.
=> (main) Set Dependabot to weekly

.github/workflows/build.yaml
Fix CI error when validating artifact signature
No
No
=> (v2.2.x) Fix signature validation in CI

docs/modules/plugin/pages/v3-migration-guide.adoc
Fix some mistakes found in the migration guide. Because nothing can ever go according to plan :smiley: 
no
Yes, now the examples are correct.
=> (main) Small fixes to v3 migration guide

README.adoc
Now that v3.0.0 is out, and v2.2.x is still supported for fixes, it was necessary to explain that in README for both users and maintainers.
We could add to Antora docs, but this seems a more appropriate place as this is the first point of entry for most users (afaik).
no
=> (main) Explain goals for v3.x.x and v2.2.x branches in README

docs/modules/plugin/pages/compatibility-matrix.adoc, docs/modules/site-integration/pages/compatibility-matrix.adoc, docs/modules/site-integration/pages/exposed-metadata.adoc
Update the compatibility matrix information for plugin and doxia modules now that v3.0.0 is out 🎉 
no
no
=> (main) Review and fixes for compatibility-matrix.adoc

README.adoc
A simple review of README to ensure we don't than unused attributes that require periodic updates.
no
no
=> Improve getting started and use version attributes

pom.xml
Bumping to the latest version of AsciidoctorJ 2.5.12 and required JRuby bump.
no
no
=> (v2.2.x) Bump AsciidoctorJ to v2.5.12 and JRuby to v9.4.6.0

.github/workflows/build.yaml
=> Use macos-13 in CI which supports Java8

CHANGELOG.adoc
Reminder for future self. I am thinking releasing as 3.1.0 instead of 3.0.1, and we need a feature to sell that :smile: 
=> Update CHANGELOG about AsciidoctorJ 3 support

README_zh-CN.adoc, asciidoctor-converter-doxia-module/src/it/maven-site-plugin/pom.xml, asciidoctor-parser-doxia-module/src/it/maven-site-plugin/pom.xml, docs/modules/site-integration/pages/converter-module-setup-and-configuration.adoc, docs/modules/site-integration/pages/parser-module-setup-and-configuration.adoc
Update docs to show how to also ignore internal (underscore prefixed) paths in site integration.
No
No. Things will go life as soon as merged and "Deploy Docs" GH action runs.
Fixes #750
=> Document how to ignore internal paths in site modules

asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/parser/processors/ExampleNodeProcessor.java, asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/parser/processors/ImageNodeProcessor.java, asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/parser/processors/SectionNodeProcessor.java, asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/parser/processors/TableNodeProcessor.java, asciidoctor-parser-doxia-module/src/test/java/org/asciidoctor/maven/site/parser/processors/ParagraphNodeProcessorTest.java, asciidoctor-parser-doxia-module/src/test/java/org/asciidoctor/maven/site/parser/processors/PreambleNodeProcessorTest.java, asciidoctor-parser-doxia-module/src/test/java/org/asciidoctor/maven/site/parser/processors/TableNodeProcessorTest.java, asciidoctor-parser-doxia-module/src/test/java/org/asciidoctor/maven/site/parser/processors/test/Html.java
Issue #937 
No
Added tests for:
* Paragraphs
* Preamble
* Tables
* Lists
* Captions
Fixes #937
=> Vadilate inline images are correctly presented

docs/modules/site-integration/pages/converter-module-setup-and-configuration.adoc, docs/modules/site-integration/pages/parser-module-setup-and-configuration.adoc
Simply updating docs for next release :rocket:
=> Update docs to graduate parser-doxia-module to Beta

CHANGELOG.adoc, README.adoc, docs/antora.yml
=> Update docs for v3.1.0 release

.github/workflows/build.yaml, .github/workflows/release.yaml
=> Add maven error output for release troubleshooting

asciidoctor-converter-doxia-module/pom.xml, asciidoctor-maven-commons/pom.xml, asciidoctor-maven-plugin/pom.xml, asciidoctor-parser-doxia-module/pom.xml, pom.xml
=> Set version to 3.1.0 for next release

CHANGELOG.adoc, asciidoctor-converter-doxia-module/src/main/java/org/asciidoctor/maven/site/AsciidoctorConverterDoxiaParser.java, asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/parser/AsciidoctorAstDoxiaParser.java, asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/parser/processors/NoOpNodeProcessor.java, asciidoctor-parser-doxia-module/src/main/java/org/asciidoctor/maven/site/parser/processors/SectionNodeProcessor.java
A simple refactor for consistency.
I could use Lombok `@Slf4j`, but eventually I want to remove it, so I am not introducing more usages.
Only for tests.
No
=> (main) Unify loggers to be static

.github/workflows/build.yaml
Prevent CI running when changing docs like CHANGELOG.
=> (main) Prevent PR pipeline running on changes in root docs

CHANGELOG.adoc, README.adoc, docs/antora.yml
For reference, https://github.com/abelsromero/asciidoctor-maven-plugin/wiki/Maven-release-steps-(manual)
=> Updates for release 3.1.1

.github/workflows/build-maven-4.yaml, pom.xml
Keeping up with Maven 4 releases to ensure the plugin is compatible and ready for when Maven 4 arrives :tada: 
No
No
=> Bump Maven 4 to RC-1

.github/workflows/build-maven-4.yaml, pom.xml
Keeping up with Maven 4 releases to ensure the plugin is compatible and ready for when Maven 4 arrives 🎉
=> Bump Maven 4 to RC-2

.github/workflows/build-maven-4.yaml, pom.xml
Keeping up with Maven 4 releases to ensure the plugin is compatible and ready for when Maven 4 arrives 🎉
n/a
n/a
=> Bump Maven 4 to RC-3

README.adoc, asciidoctor-converter-doxia-module/pom.xml, asciidoctor-maven-commons/pom.xml, asciidoctor-maven-plugin/pom.xml, asciidoctor-parser-doxia-module/pom.xml, docs/antora.yml, docs/modules/site-integration/pages/compatibility-matrix.adoc, pom.xml
Prepare next release :rocket: 
n/a
Bumping minor versions since this is a new feature.
=> Update docs for v3.2.0 release

CHANGELOG.adoc
=> Update CHANGELOG in preparation of next release(s)
